#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$RepoRoot='',
    [string]$ArchiveRoot='',
    [string]$OutputRoot='',
    [ValidateRange(100,5000)][int]$BatchRows=500,
    [ValidateRange(0,256)][int]$WorkerCount=0,
    [ValidateRange(1,1000)][int]$MinFreeGB=15,
    [switch]$ValidateInputsOnly,
    [switch]$SelfTest
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

$ExpectedArchives=7163;$ExpectedRows=9183757L;$ExpectedMalformedRows=5L;$ExpectedValidRows=9183752L
$ContextSchemaVersion='CFA_STAGE3_CONTEXT_V1';$SamplingSchemaVersion='CFA_STAGE3_SAMPLE_V2'
$UnbiasedTarget=15000;$NegativeTarget=15000;$EdgeTarget=10000
$Utf8=New-Object System.Text.UTF8Encoding($false)
$BroadAnchors=@('bitcoin','ethereum','crypto','cryptocurrency','cryptocurrencies','blockchain','token','tokens','stablecoin','stablecoins','defi','decentralized finance','web3','nft','nfts','digital asset','digital assets','digital currency','digital currencies','staking','airdrop','airdrops','wallet','wallets','altcoin','altcoins','memecoin','memecoins','crypto market','cryptocurrency market')
$SelectionHeader=@('sample_stratum','selection_rank','lineage_key','context_sha256','context_byte_length','archive_file','archive_timestamp_utc','row_ordinal','record_id','gdelt_date_utc','source_common_name','document_identifier','page_title','themes_raw','persons_raw','organizations_raw','all_names_raw','extras_raw','context_replacement_present','discovery_candidate','discovery_broad_anchor','discovery_candidate_asset_count','discovery_candidate_asset_ids','discovery_candidate_aliases')

function Write-Utf8NoBom{param([string]$Path,[string]$Content);$parent=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $parent -PathType Container)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[System.IO.File]::WriteAllText($Path,$Content,(New-Object System.Text.UTF8Encoding($false)))}
function Csv{param([AllowNull()][object]$Value);$s=if($null-eq$Value){''}else{[string]$Value};if($s.Contains('"')){$s=$s.Replace('"','""')};if($s.Contains(',')-or$s.Contains('"')-or$s.Contains("`r")-or$s.Contains("`n")){return '"'+$s+'"'};return $s}
function Write-CsvRow{param([System.IO.StreamWriter]$Writer,[object[]]$Values);$Writer.WriteLine((@($Values|ForEach-Object{Csv $_})-join','))}
function Open-CsvWriter{param([string]$Path,[string[]]$Header);$w=New-Object System.IO.StreamWriter -ArgumentList $Path,$false,$Utf8;Write-CsvRow $w $Header;return $w}
function Get-FreeGB{param([string]$Path);$full=[System.IO.Path]::GetFullPath($Path);$root=[System.IO.Path]::GetPathRoot($full);$d=New-Object System.IO.DriveInfo $root;return [math]::Round($d.AvailableFreeSpace/1GB,2)}

function Build-ReadingPopulation{
    param([string]$SelectionPath,[string]$ReadingPath,[string]$OutputRoot,[int]$BatchRows)
    $readingHeader=@('context_sha256','context_byte_length','selection_occurrence_count','selection_strata','representative_lineage_key','archive_file','archive_timestamp_utc','row_ordinal','record_id','gdelt_date_utc','source_common_name','document_identifier','page_title','themes_raw','persons_raw','organizations_raw','all_names_raw','extras_raw','context_replacement_present','discovery_candidate','discovery_broad_anchor','discovery_candidate_asset_count','discovery_candidate_asset_ids','discovery_candidate_aliases')
    $states=@{}
    foreach($r in @(Import-Csv -LiteralPath $SelectionPath -Encoding UTF8)){
        $hash=[string]$r.context_sha256
        if(-not$states.ContainsKey($hash)){$states[$hash]=[pscustomobject]@{row=$r;count=0;strata=@{}}}
        $st=$states[$hash];$st.count=[int]$st.count+1;$st.strata[[string]$r.sample_stratum]=$true
    }
    $rw=Open-CsvWriter $ReadingPath $readingHeader
    $manifest=@();$batchWriter=$null;$batchIndex=0;$batchCount=0;$batchStrata=@{};$batchFile=''
    try{
        foreach($hash in @($states.Keys|Sort-Object)){
            $st=$states[$hash];$r=$st.row;$strata=(@($st.strata.Keys|Sort-Object)-join'|')
            $values=@($r.context_sha256,$r.context_byte_length,$st.count,$strata,$r.lineage_key,$r.archive_file,$r.archive_timestamp_utc,$r.row_ordinal,$r.record_id,$r.gdelt_date_utc,$r.source_common_name,$r.document_identifier,$r.page_title,$r.themes_raw,$r.persons_raw,$r.organizations_raw,$r.all_names_raw,$r.extras_raw,$r.context_replacement_present,$r.discovery_candidate,$r.discovery_broad_anchor,$r.discovery_candidate_asset_count,$r.discovery_candidate_asset_ids,$r.discovery_candidate_aliases)
            Write-CsvRow $rw $values
            if($null-eq$batchWriter-or$batchCount-ge$BatchRows){
                if($null-ne$batchWriter){$batchWriter.Dispose();$bp=Join-Path $OutputRoot $batchFile;$manifest += [pscustomobject]@{file=$batchFile;rows=$batchCount;bytes=(Get-Item -LiteralPath $bp).Length;sha256=(Get-FileHash -LiteralPath $bp -Algorithm SHA256).Hash.ToLowerInvariant();stratum_counts=($batchStrata.GetEnumerator()|Sort-Object Name|ForEach-Object{$_.Name+'='+$_.Value})-join'|'}}
                $batchIndex++;$batchFile=('context-discovery-batch-{0:D4}.csv'-f$batchIndex);$batchWriter=Open-CsvWriter (Join-Path $OutputRoot $batchFile) $readingHeader;$batchCount=0;$batchStrata=@{}
            }
            Write-CsvRow $batchWriter $values;$batchCount++
            foreach($ss in $st.strata.Keys){if(-not$batchStrata.ContainsKey($ss)){$batchStrata[$ss]=0};$batchStrata[$ss]=[int]$batchStrata[$ss]+1}
        }
    }finally{
        $rw.Dispose()
        if($null-ne$batchWriter){$batchWriter.Dispose();$bp=Join-Path $OutputRoot $batchFile;$manifest += [pscustomobject]@{file=$batchFile;rows=$batchCount;bytes=(Get-Item -LiteralPath $bp).Length;sha256=(Get-FileHash -LiteralPath $bp -Algorithm SHA256).Hash.ToLowerInvariant();stratum_counts=($batchStrata.GetEnumerator()|Sort-Object Name|ForEach-Object{$_.Name+'='+$_.Value})-join'|'}}
    }
    return [pscustomobject]@{unique_contexts=$states.Count;manifest=$manifest;header=$readingHeader}
}

$CSharp=@'
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
namespace CfaStage3ContextV3 {
public sealed class CandidateKey { public string Rank,LineageKey,ArchiveName,RecordId; public long RowOrdinal; public bool Candidate; }
public sealed class SelectedKey { public string Stratum,Rank,LineageKey,ArchiveName,RecordId; public long RowOrdinal; public bool Candidate; }
public sealed class ScanResult { public int LogicalProcessorCount,WorkerCount,ArchivesProcessed; public long TotalRows,MalformedRows,MissingCriticalRows,ValidRows,BlankTitleRows,BlankThemesRows,BlankPersonsRows,BlankOrganizationsRows,BlankAllNamesRows,BlankSourceRows,ReplacementRows,DiscoveryCandidates,DiscoveryNegatives; public double ElapsedSeconds,RowsPerSecond; public CandidateKey[] UnbiasedCandidates,NegativeCandidates,EdgeCandidates; }
public sealed class SelectionResult { public SelectedKey[] Selected; public int UnbiasedCount,NegativeCount,EdgeCount; }
public sealed class MaterializeResult { public int RowsWritten; public double ElapsedSeconds; }
internal sealed class RowFields { public string RecordId,Date,Source,Document,Themes,Persons,Organizations,AllNames,Extras; }
internal sealed class DiscoverySignals { public bool Candidate,BroadAnchor; public string CandidateAssets,CandidateAliases; public int CandidateAssetCount; }
internal sealed class WorkerSummary { public int Archives; public long TotalRows,MalformedRows,MissingCriticalRows,ValidRows,BlankTitleRows,BlankThemesRows,BlankPersonsRows,BlankOrganizationsRows,BlankAllNamesRows,BlankSourceRows,ReplacementRows,DiscoveryCandidates,DiscoveryNegatives; public List<CandidateKey> U=new List<CandidateKey>(),N=new List<CandidateKey>(),E=new List<CandidateKey>(); }
public static class Engine {
const string ContextSchemaVersion="CFA_STAGE3_CONTEXT_V1",SamplingSchemaVersion="CFA_STAGE3_SAMPLE_V2";
const int UnbiasedRankByteExclusive=2,NegativeRankByteExclusive=2,EdgeRankByteExclusive=32;
static readonly UTF8Encoding Utf8=new UTF8Encoding(false); static Regex AliasRegex,AnchorRegex; static Dictionary<string,string[]> AliasLookup; static readonly object ProgressLock=new object(); static long ProgressRows,ProgressArchives,NextProgressRows; static int ProgressArchiveTotal; static long ProgressExpectedRows; static Stopwatch ProgressClock;
public static ScanResult Scan(string[] archives,string[] aliasTexts,string[] baseIds,string[] anchors,int workerCount,long expectedRows){if(archives==null||archives.Length==0)throw new ArgumentException("archives");BuildTools(aliasTexts,baseIds,anchors);int logical=Environment.ProcessorCount,degree=workerCount<=0?logical:workerCount;if(degree<1)degree=1;if(degree>archives.Length)degree=archives.Length;Console.WriteLine("Context inventory V3 pass1: workers="+degree+" | logical_processors="+logical+" | archives="+archives.Length);ProgressRows=0;ProgressArchives=0;NextProgressRows=250000;ProgressArchiveTotal=archives.Length;ProgressExpectedRows=expectedRows;ProgressClock=Stopwatch.StartNew();WorkerSummary[] ws=new WorkerSummary[degree];ParallelOptions po=new ParallelOptions();po.MaxDegreeOfParallelism=degree;Parallel.For(0,degree,po,delegate(int worker){WorkerSummary s=new WorkerSummary();int start=(archives.Length*worker)/degree,end=(archives.Length*(worker+1))/degree;for(int i=start;i<end;i++){ProcessArchive(archives[i],s);}ws[worker]=s;});ProgressClock.Stop();ScanResult r=new ScanResult();r.LogicalProcessorCount=logical;r.WorkerCount=degree;List<CandidateKey> u=new List<CandidateKey>(),n=new List<CandidateKey>(),e=new List<CandidateKey>();foreach(WorkerSummary s in ws){r.ArchivesProcessed+=s.Archives;r.TotalRows+=s.TotalRows;r.MalformedRows+=s.MalformedRows;r.MissingCriticalRows+=s.MissingCriticalRows;r.ValidRows+=s.ValidRows;r.BlankTitleRows+=s.BlankTitleRows;r.BlankThemesRows+=s.BlankThemesRows;r.BlankPersonsRows+=s.BlankPersonsRows;r.BlankOrganizationsRows+=s.BlankOrganizationsRows;r.BlankAllNamesRows+=s.BlankAllNamesRows;r.BlankSourceRows+=s.BlankSourceRows;r.ReplacementRows+=s.ReplacementRows;r.DiscoveryCandidates+=s.DiscoveryCandidates;r.DiscoveryNegatives+=s.DiscoveryNegatives;u.AddRange(s.U);n.AddRange(s.N);e.AddRange(s.E);}CandidateComparer cmp=new CandidateComparer();u.Sort(cmp);n.Sort(cmp);e.Sort(cmp);r.UnbiasedCandidates=u.ToArray();r.NegativeCandidates=n.ToArray();r.EdgeCandidates=e.ToArray();r.ElapsedSeconds=ProgressClock.Elapsed.TotalSeconds;r.RowsPerSecond=r.ElapsedSeconds>0?(r.TotalRows/r.ElapsedSeconds):0;return r;}
public static SelectionResult Select(CandidateKey[] u,CandidateKey[] n,CandidateKey[] e,int uTarget,int nTarget,int eTarget){SelectionResult r=new SelectionResult();List<SelectedKey> selected=new List<SelectedKey>();HashSet<string> seen=new HashSet<string>(StringComparer.Ordinal);Take(u,uTarget,"UNBIASED",seen,selected,ref r.UnbiasedCount);Take(n,nTarget,"RETRIEVAL_NEGATIVE",seen,selected,ref r.NegativeCount);Take(e,eTarget,"ASSET_EDGE",seen,selected,ref r.EdgeCount);r.Selected=selected.ToArray();return r;}
static void Take(CandidateKey[] src,int target,string stratum,HashSet<string> seen,List<SelectedKey> dst,ref int count){if(src==null)return;for(int i=0;i<src.Length&&count<target;i++){CandidateKey c=src[i];if(!seen.Add(c.LineageKey))continue;SelectedKey s=new SelectedKey();s.Stratum=stratum;s.Rank=c.Rank;s.LineageKey=c.LineageKey;s.ArchiveName=c.ArchiveName;s.RowOrdinal=c.RowOrdinal;s.RecordId=c.RecordId;s.Candidate=c.Candidate;dst.Add(s);count++;}}
public static MaterializeResult Materialize(string[] archives,SelectedKey[] selected,string outputPath,string tempRoot,int workerCount){if(selected==null)throw new ArgumentNullException("selected");Directory.CreateDirectory(tempRoot);Dictionary<string,Dictionary<long,SelectedKey>> byArchive=new Dictionary<string,Dictionary<long,SelectedKey>>(StringComparer.Ordinal);foreach(SelectedKey s in selected){Dictionary<long,SelectedKey> rows;if(!byArchive.TryGetValue(s.ArchiveName,out rows)){rows=new Dictionary<long,SelectedKey>();byArchive.Add(s.ArchiveName,rows);}rows.Add(s.RowOrdinal,s);}int degree=workerCount<=0?Environment.ProcessorCount:workerCount;if(degree<1)degree=1;if(degree>archives.Length)degree=archives.Length;string[] workerFiles=new string[degree];int[] counts=new int[degree];Stopwatch sw=Stopwatch.StartNew();ParallelOptions po=new ParallelOptions();po.MaxDegreeOfParallelism=degree;Parallel.For(0,degree,po,delegate(int worker){int start=(archives.Length*worker)/degree,end=(archives.Length*(worker+1))/degree;string wf=Path.Combine(tempRoot,String.Format(CultureInfo.InvariantCulture,"materialized-{0:D3}.csv",worker));workerFiles[worker]=wf;using(StreamWriter w=new StreamWriter(wf,false,new UTF8Encoding(false),65536)){w.WriteLine(Header);for(int i=start;i<end;i++){string name=Path.GetFileName(archives[i]);Dictionary<long,SelectedKey> wanted;if(!byArchive.TryGetValue(name,out wanted))continue;counts[worker]+=MaterializeArchive(archives[i],wanted,w);}}});using(StreamWriter outw=new StreamWriter(outputPath,false,new UTF8Encoding(false),65536)){outw.WriteLine(Header);for(int worker=0;worker<degree;worker++){using(StreamReader rr=new StreamReader(workerFiles[worker],new UTF8Encoding(false),false,65536)){rr.ReadLine();string line;while((line=rr.ReadLine())!=null)outw.WriteLine(line);}File.Delete(workerFiles[worker]);}}sw.Stop();MaterializeResult mr=new MaterializeResult();for(int i=0;i<counts.Length;i++)mr.RowsWritten+=counts[i];mr.ElapsedSeconds=sw.Elapsed.TotalSeconds;return mr;}
static int MaterializeArchive(string path,Dictionary<long,SelectedKey> wanted,StreamWriter w){string name=Path.GetFileName(path),stamp=name.Substring(0,14);DateTime dt=DateTime.ParseExact(stamp,"yyyyMMddHHmmss",CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal|DateTimeStyles.AdjustToUniversal);string ats=dt.ToString("yyyy-MM-ddTHH:mm:ssZ",CultureInfo.InvariantCulture);long max=0;foreach(long k in wanted.Keys)if(k>max)max=k;int written=0;using(ZipArchive zip=ZipFile.OpenRead(path)){ZipArchiveEntry entry=OneEntry(zip,name);using(Stream es=entry.Open())using(StreamReader reader=new StreamReader(es,new UTF8Encoding(false,false),false,65536)){string line;long ro=0;using(SHA256 contextHasher=SHA256.Create()){while(ro<max&&(line=reader.ReadLine())!=null){ro++;SelectedKey sk;if(!wanted.TryGetValue(ro,out sk))continue;RowFields f;if(!TryParseFields(line,out f))throw new InvalidDataException("Selected row became malformed at "+name+" row "+ro);if(!String.Equals(f.RecordId,sk.RecordId,StringComparison.Ordinal))throw new InvalidDataException("Selected record-id mismatch at "+name+" row "+ro);string title=GetPageTitle(f.Extras);bool replacement=ContainsReplacement(f.Source,f.Document,title,f.Themes,f.Persons,f.Organizations,f.AllNames,f.Extras);DiscoverySignals sig=GetSignals(title,f.Document,f.Themes,f.Persons,f.Organizations,f.AllNames);if(sig.Candidate!=sk.Candidate)throw new InvalidDataException("Pass1/pass2 candidate mismatch at "+name+" row "+ro);string ch;int cb;ComputeContextHash(contextHasher,f.Source,f.Document,title,f.Themes,f.Persons,f.Organizations,f.AllNames,f.Extras,out ch,out cb);string[] v=new string[]{sk.Stratum,sk.Rank,sk.LineageKey,ch,cb.ToString(CultureInfo.InvariantCulture),name,ats,ro.ToString(CultureInfo.InvariantCulture),f.RecordId??String.Empty,f.Date??String.Empty,f.Source??String.Empty,f.Document??String.Empty,title??String.Empty,f.Themes??String.Empty,f.Persons??String.Empty,f.Organizations??String.Empty,f.AllNames??String.Empty,f.Extras??String.Empty,replacement.ToString(),sig.Candidate.ToString(),sig.BroadAnchor.ToString(),sig.CandidateAssetCount.ToString(CultureInfo.InvariantCulture),sig.CandidateAssets??String.Empty,sig.CandidateAliases??String.Empty};WriteCsvRow(w,v);written++;}}}}if(written!=wanted.Count)throw new InvalidDataException("Selected row materialization count mismatch in "+name+": expected "+wanted.Count+", wrote "+written);return written;}
static void ProcessArchive(string path,WorkerSummary s){string name=Path.GetFileName(path);long ar=0;using(SHA256 sampling=SHA256.Create())using(ZipArchive zip=ZipFile.OpenRead(path)){ZipArchiveEntry entry=OneEntry(zip,name);using(Stream es=entry.Open())using(StreamReader reader=new StreamReader(es,new UTF8Encoding(false,false),false,65536)){string line;long ro=0;while((line=reader.ReadLine())!=null){ro++;ar++;s.TotalRows++;RowFields f;if(!TryParseFields(line,out f)){s.MalformedRows++;continue;}if(String.IsNullOrWhiteSpace(f.RecordId)||!IsFourteenDigits(f.Date)||String.IsNullOrWhiteSpace(f.Document)){s.MissingCriticalRows++;continue;}s.ValidRows++;string title=GetPageTitle(f.Extras);if(String.IsNullOrWhiteSpace(title))s.BlankTitleRows++;if(String.IsNullOrWhiteSpace(f.Themes))s.BlankThemesRows++;if(String.IsNullOrWhiteSpace(f.Persons))s.BlankPersonsRows++;if(String.IsNullOrWhiteSpace(f.Organizations))s.BlankOrganizationsRows++;if(String.IsNullOrWhiteSpace(f.AllNames))s.BlankAllNamesRows++;if(String.IsNullOrWhiteSpace(f.Source))s.BlankSourceRows++;if(ContainsReplacement(f.Source,f.Document,title,f.Themes,f.Persons,f.Organizations,f.AllNames,f.Extras))s.ReplacementRows++;bool candidate=TestCandidate(title,f.Document,f.Themes,f.Persons,f.Organizations,f.AllNames);if(candidate)s.DiscoveryCandidates++;else s.DiscoveryNegatives++;byte[] rb=ComputeSamplingRank(sampling,name,ro,f.RecordId);string hex=null;if((int)rb[0]<UnbiasedRankByteExclusive){hex=BytesToHex(rb);s.U.Add(Key(hex,name,ro,f.RecordId,candidate));}if(!candidate&&(int)rb[1]<NegativeRankByteExclusive){if(hex==null)hex=BytesToHex(rb);s.N.Add(Key(RotateHex(hex,1),name,ro,f.RecordId,candidate));}if(candidate&&(int)rb[2]<EdgeRankByteExclusive){if(hex==null)hex=BytesToHex(rb);s.E.Add(Key(RotateHex(hex,2),name,ro,f.RecordId,candidate));}}}}s.Archives++;long rn=Interlocked.Add(ref ProgressRows,ar),an=Interlocked.Increment(ref ProgressArchives);MaybeReport(rn,an);}
static CandidateKey Key(string rank,string archive,long ro,string id,bool candidate){CandidateKey c=new CandidateKey();c.Rank=rank;c.ArchiveName=archive;c.RowOrdinal=ro;c.RecordId=id;c.Candidate=candidate;c.LineageKey=archive+"|"+ro.ToString(CultureInfo.InvariantCulture)+"|"+id;return c;}
static ZipArchiveEntry OneEntry(ZipArchive z,string name){ZipArchiveEntry entry=null;int n=0;foreach(ZipArchiveEntry e in z.Entries){if(!String.IsNullOrWhiteSpace(e.Name)){entry=e;n++;}}if(n!=1||entry==null)throw new InvalidDataException("Expected one data entry in "+name+"; observed "+n);return entry;}
static void MaybeReport(long rows,long archives){lock(ProgressLock){if(rows<NextProgressRows&&archives%250!=0&&archives!=ProgressArchiveTotal)return;while(rows>=NextProgressRows)NextProgressRows+=250000;double sec=ProgressClock.Elapsed.TotalSeconds,rate=sec>0?rows/sec:0;Console.WriteLine("Context inventory V3 progress: archives="+archives+"/"+ProgressArchiveTotal+" | rows="+rows+"/"+ProgressExpectedRows+" | "+Math.Round(rate,1).ToString(CultureInfo.InvariantCulture)+" rows/sec");}}
static void BuildTools(string[] aliases,string[] bases,string[] anchors){if(aliases==null||bases==null||aliases.Length!=bases.Length)throw new ArgumentException("alias inputs");Dictionary<string,HashSet<string>> tmp=new Dictionary<string,HashSet<string>>(StringComparer.OrdinalIgnoreCase);HashSet<string> ua=new HashSet<string>(StringComparer.OrdinalIgnoreCase);for(int i=0;i<aliases.Length;i++){string a=(aliases[i]??String.Empty).Trim(),b=(bases[i]??String.Empty).Trim();if(a.Length==0||b.Length==0)throw new InvalidOperationException("blank alias");ua.Add(a);HashSet<string> hs;if(!tmp.TryGetValue(a,out hs)){hs=new HashSet<string>(StringComparer.Ordinal);tmp.Add(a,hs);}hs.Add(b);}AliasLookup=new Dictionary<string,string[]>(StringComparer.OrdinalIgnoreCase);foreach(KeyValuePair<string,HashSet<string>> kv in tmp){string[] ar=new string[kv.Value.Count];kv.Value.CopyTo(ar);Array.Sort(ar,StringComparer.Ordinal);AliasLookup.Add(kv.Key,ar);}List<string> al=new List<string>(ua);al.Sort(delegate(string a,string b){int c=b.Length.CompareTo(a.Length);return c!=0?c:StringComparer.OrdinalIgnoreCase.Compare(a,b);});AliasRegex=BuildRegex(al);List<string> aa=new List<string>();for(int i=0;i<anchors.Length;i++){string v=(anchors[i]??String.Empty).Trim();if(v.Length>0&&!aa.Contains(v))aa.Add(v);}aa.Sort(delegate(string a,string b){int c=b.Length.CompareTo(a.Length);return c!=0?c:StringComparer.OrdinalIgnoreCase.Compare(a,b);});AnchorRegex=BuildRegex(aa);}
static Regex BuildRegex(List<string> items){StringBuilder b=new StringBuilder();b.Append("(?<![\\p{L}\\p{N}])(?:");for(int i=0;i<items.Count;i++){if(i>0)b.Append("|");b.Append(Regex.Escape(items[i]));}b.Append(")(?![\\p{L}\\p{N}])");return new Regex(b.ToString(),RegexOptions.IgnoreCase|RegexOptions.CultureInvariant|RegexOptions.Compiled);}
static bool TryParseFields(string line,out RowFields f){f=new RowFields();int col=0,start=0,len=line.Length;for(int i=0;i<=len;i++){if(i==len||line[i]=='\t'){int n=i-start;switch(col){case 0:f.RecordId=line.Substring(start,n);break;case 1:f.Date=line.Substring(start,n);break;case 3:f.Source=line.Substring(start,n);break;case 4:f.Document=line.Substring(start,n);break;case 8:f.Themes=line.Substring(start,n);break;case 12:f.Persons=line.Substring(start,n);break;case 14:f.Organizations=line.Substring(start,n);break;case 23:f.AllNames=line.Substring(start,n);break;case 26:f.Extras=line.Substring(start,n);break;}col++;start=i+1;}}return col==27;}
static bool IsFourteenDigits(string s){if(s==null||s.Length!=14)return false;for(int i=0;i<14;i++)if(s[i]<'0'||s[i]>'9')return false;return true;}
static string GetPageTitle(string x){if(String.IsNullOrWhiteSpace(x))return String.Empty;const string o="<PAGE_TITLE>",c="</PAGE_TITLE>";int s=x.IndexOf(o,StringComparison.OrdinalIgnoreCase);if(s<0)return String.Empty;int cs=s+o.Length,e=x.IndexOf(c,cs,StringComparison.OrdinalIgnoreCase);if(e<cs)return String.Empty;return WebUtility.HtmlDecode(x.Substring(cs,e-cs));}
static bool ContainsReplacement(params string[] v){for(int i=0;i<v.Length;i++){string s=v[i];if(s!=null&&s.IndexOf('\uFFFD')>=0)return true;}return false;}
static bool TestCandidate(params string[] v){for(int i=0;i<v.Length;i++){string s=v[i];if(String.IsNullOrEmpty(s))continue;if(AnchorRegex.IsMatch(s)||AliasRegex.IsMatch(s))return true;}return false;}
static DiscoverySignals GetSignals(string title,string url,string themes,string persons,string orgs,string names){string text=String.Join("\n",new string[]{title??String.Empty,url??String.Empty,themes??String.Empty,persons??String.Empty,orgs??String.Empty,names??String.Empty});SortedSet<string> assets=new SortedSet<string>(StringComparer.Ordinal),aliases=new SortedSet<string>(StringComparer.OrdinalIgnoreCase);foreach(Match m in AliasRegex.Matches(text)){string[] bs;if(AliasLookup.TryGetValue(m.Value,out bs)){aliases.Add(m.Value);for(int i=0;i<bs.Length;i++)assets.Add(bs[i]);}}DiscoverySignals s=new DiscoverySignals();s.BroadAnchor=AnchorRegex.IsMatch(text);s.Candidate=s.BroadAnchor||assets.Count>0;s.CandidateAssets=String.Join("|",new List<string>(assets).ToArray());s.CandidateAliases=String.Join("|",new List<string>(aliases).ToArray());s.CandidateAssetCount=assets.Count;return s;}
static byte[] ComputeSamplingRank(SHA256 h,string a,long r,string id){return h.ComputeHash(Utf8.GetBytes(SamplingSchemaVersion+"|"+a+"|"+r.ToString(CultureInfo.InvariantCulture)+"|"+id));}
static void ComputeContextHash(SHA256 h,string source,string document,string title,string themes,string persons,string orgs,string names,string extras,out string hash,out int len){string[] f=new string[]{source,document,title,themes,persons,orgs,names,extras};StringBuilder b=new StringBuilder();b.Append(ContextSchemaVersion).Append("|");for(int i=0;i<f.Length;i++){string s=f[i]??String.Empty;int n=Utf8.GetByteCount(s);b.Append(n.ToString(CultureInfo.InvariantCulture)).Append(":").Append(s).Append("|");}byte[] bytes=Utf8.GetBytes(b.ToString());hash=BytesToHex(h.ComputeHash(bytes));len=bytes.Length;}
static string BytesToHex(byte[] b){return BitConverter.ToString(b).Replace("-",String.Empty).ToLowerInvariant();} static string RotateHex(string h,int off){int c=off*2;return c<=0?h:h.Substring(c)+h.Substring(0,c);}
static void WriteCsvRow(StreamWriter w,string[] v){for(int i=0;i<v.Length;i++){if(i>0)w.Write(',');w.Write(Csv(v[i]));}w.WriteLine();} static string Csv(string value){string s=value??String.Empty;bool q=s.IndexOf(',')>=0||s.IndexOf('"')>=0||s.IndexOf('\r')>=0||s.IndexOf('\n')>=0;if(s.IndexOf('"')>=0)s=s.Replace("\"","\"\"");return q?"\""+s+"\"":s;}
public const string Header="sample_stratum,selection_rank,lineage_key,context_sha256,context_byte_length,archive_file,archive_timestamp_utc,row_ordinal,record_id,gdelt_date_utc,source_common_name,document_identifier,page_title,themes_raw,persons_raw,organizations_raw,all_names_raw,extras_raw,context_replacement_present,discovery_candidate,discovery_broad_anchor,discovery_candidate_asset_count,discovery_candidate_asset_ids,discovery_candidate_aliases";
sealed class CandidateComparer:IComparer<CandidateKey>{public int Compare(CandidateKey a,CandidateKey b){int c=StringComparer.Ordinal.Compare(a.Rank,b.Rank);if(c!=0)return c;return StringComparer.Ordinal.Compare(a.LineageKey,b.LineageKey);}}
}}
'@
function Install-Engine{if('CfaStage3ContextV3.Engine' -as [type]){return};if($PSVersionTable.PSVersion.Major-ge6){Add-Type -TypeDefinition $CSharp -Language CSharp}else{$refs=@([System.IO.Compression.ZipArchive].Assembly.Location,[System.IO.Compression.ZipFile].Assembly.Location)|Where-Object{-not[string]::IsNullOrWhiteSpace($_)}|Sort-Object -Unique;Add-Type -TypeDefinition $CSharp -Language CSharp -ReferencedAssemblies $refs}}

function New-SyntheticGkgArchive{param([string]$Path,[int]$Seed,[int]$Rows);$dir=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};$fs=[System.IO.File]::Open($Path,[System.IO.FileMode]::Create,[System.IO.FileAccess]::ReadWrite,[System.IO.FileShare]::None);$zip=[System.IO.Compression.ZipArchive]::new($fs,[System.IO.Compression.ZipArchiveMode]::Create,$false);try{$entry=$zip.CreateEntry(([System.IO.Path]::GetFileNameWithoutExtension($Path)+'.csv'),[System.IO.Compression.CompressionLevel]::Fastest);$writer=New-Object System.IO.StreamWriter -ArgumentList $entry.Open(),$Utf8;try{foreach($i in 1..$Rows){$f=New-Object string[] 27;$f[0]="r-$Seed-$i";$f[1]='20250401000000';$f[3]='example.test';$f[4]="https://example.test/$Seed/$i";if(($i%3)-eq0){$f[8]='ECON_BITCOIN';$f[23]='Avalanche';$f[26]='<PAGE_TITLE>Avalanche (AVAX) and Bitcoin update</PAGE_TITLE>'}elseif(($i%5)-eq0){$f[14]='KeyCorp';$f[23]='KeyCorp';$f[26]='<PAGE_TITLE>KeyCorp (NYSE:KEY) stock update</PAGE_TITLE>'}else{$f[26]='<PAGE_TITLE>Local weather forecast</PAGE_TITLE>'};$writer.WriteLine(($f-join"`t"))}}finally{$writer.Dispose()}}finally{$zip.Dispose();$fs.Dispose()}}

function Invoke-SelfTest{
    Install-Engine;$root=Join-Path ([System.IO.Path]::GetTempPath()) ('cfa-context-v3-'+[guid]::NewGuid().ToString('N'));$src=Join-Path $root 'src';New-Item -ItemType Directory -Path $src -Force|Out-Null
    try{
        $paths=@();foreach($n in 0..11){$name=([datetime]::new(2025,4,1,0,0,0,[DateTimeKind]::Utc).AddMinutes(15*$n).ToString('yyyyMMddHHmmss'))+'.gkg.csv.zip';$p=Join-Path $src $name;New-SyntheticGkgArchive $p ($n+1) 200;$paths+=$p}
        $aliases=@('AVAX','KEY');$bases=@('AVAX','KEY')
        $one=[CfaStage3ContextV3.Engine]::Scan($paths,$aliases,$bases,$BroadAnchors,1,2400)
        $mw=[math]::Min(4,[Environment]::ProcessorCount);if($mw-lt1){$mw=1};$many=[CfaStage3ContextV3.Engine]::Scan($paths,$aliases,$bases,$BroadAnchors,$mw,2400)
        foreach($p in @('ArchivesProcessed','TotalRows','MalformedRows','MissingCriticalRows','ValidRows','DiscoveryCandidates','DiscoveryNegatives')){if([string]$one.$p-ne[string]$many.$p){throw "parallel counter mismatch: $p"}}
        $s1=[CfaStage3ContextV3.Engine]::Select($one.UnbiasedCandidates,$one.NegativeCandidates,$one.EdgeCandidates,5,5,5);$sN=[CfaStage3ContextV3.Engine]::Select($many.UnbiasedCandidates,$many.NegativeCandidates,$many.EdgeCandidates,5,5,5)
        $a=@($s1.Selected|ForEach-Object{$_.Stratum+'|'+$_.Rank+'|'+$_.LineageKey});$b=@($sN.Selected|ForEach-Object{$_.Stratum+'|'+$_.Rank+'|'+$_.LineageKey});if(($a-join"`n")-ne($b-join"`n")){throw 'parallel selection determinism'}
        $o1=Join-Path $root 'one.csv';$oN=Join-Path $root 'many.csv';$t1=Join-Path $root 't1';$tN=Join-Path $root 'tn';New-Item -ItemType Directory -Path $t1,$tN -Force|Out-Null
        $m1=[CfaStage3ContextV3.Engine]::Materialize($paths,$s1.Selected,$o1,$t1,1);$mN=[CfaStage3ContextV3.Engine]::Materialize($paths,$sN.Selected,$oN,$tN,$mw)
        if($m1.RowsWritten-ne$mN.RowsWritten-or(Get-FileHash $o1 -Algorithm SHA256).Hash-ne(Get-FileHash $oN -Algorithm SHA256).Hash){throw 'parallel materialization determinism'}
        Write-Host ('SELF-TEST: PASS | logical_processors='+[Environment]::ProcessorCount+' | workers_tested='+$mw)
    }finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}}

try{
    Install-Engine
    if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).ProviderPath
    $aliasPath=Join-Path $RepoRoot 'candidate-analysis\CFA-Stage3-News-Aliases.csv';if(-not(Test-Path -LiteralPath $aliasPath -PathType Leaf)){throw "Alias registry missing: $aliasPath"};$aliases=@(Import-Csv -LiteralPath $aliasPath -Encoding UTF8);if($aliases.Count-ne470){throw "Expected 470 alias rows; observed $($aliases.Count)."};$aliasTexts=@($aliases|ForEach-Object{([string]$_.alias_text).Trim()});$baseIds=@($aliases|ForEach-Object{([string]$_.base_asset_id).Trim()})
    $effectiveWorkers=if($WorkerCount-le0){[Environment]::ProcessorCount}else{$WorkerCount}
    if($ValidateInputsOnly){Write-Host ('CFA STAGE 3 CONTEXT V3 INPUTS: PASS | aliases=470 | sampling='+$SamplingSchemaVersion+' | logical_processors='+[Environment]::ProcessorCount+' | workers='+$effectiveWorkers);exit 0}
    $documents=[Environment]::GetFolderPath('MyDocuments');if([string]::IsNullOrWhiteSpace($ArchiveRoot)){$ArchiveRoot=Join-Path $documents 'CFA-local\gdelt-gkg-q2-2025'};if(-not(Test-Path -LiteralPath $ArchiveRoot -PathType Container)){throw "Archive root missing: $ArchiveRoot"};$ArchiveRoot=(Resolve-Path -LiteralPath $ArchiveRoot).ProviderPath
    $files=@(Get-ChildItem -LiteralPath $ArchiveRoot -Recurse -File -Filter '*.gkg.csv.zip'|Where-Object{$_.Name-match'^\d{14}\.gkg\.csv\.zip$'}|Sort-Object Name);if($files.Count-ne$ExpectedArchives){throw "Expected $ExpectedArchives archives; observed $($files.Count)."}
    if([string]::IsNullOrWhiteSpace($OutputRoot)){$parent=Join-Path $documents 'CFA-local\stage3-context-inventory';if(-not(Test-Path -LiteralPath $parent -PathType Container)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$OutputRoot=Join-Path $parent ((Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N'))}
    $outputParent=Split-Path -Parent $OutputRoot;if(-not(Test-Path -LiteralPath $outputParent -PathType Container)){New-Item -ItemType Directory -Path $outputParent -Force|Out-Null};$freeBefore=Get-FreeGB $outputParent;if($freeBefore-lt$MinFreeGB){throw "BLOCKED: output drive has $freeBefore GB free; at least $MinFreeGB GB is required before the bounded context run."}
    New-Item -ItemType Directory -Path $OutputRoot -Force|Out-Null;$OutputRoot=(Resolve-Path -LiteralPath $OutputRoot).ProviderPath;$tempRoot=Join-Path $OutputRoot '_temp';New-Item -ItemType Directory -Path $tempRoot -Force|Out-Null
    Write-Host ('Context inventory V3 preflight: output_free_gb='+$freeBefore+' | minimum='+$MinFreeGB+' | workers='+$effectiveWorkers)
    $scan=[CfaStage3ContextV3.Engine]::Scan(@($files.FullName),$aliasTexts,$baseIds,$BroadAnchors,$effectiveWorkers,$ExpectedRows)
    $sel=[CfaStage3ContextV3.Engine]::Select($scan.UnbiasedCandidates,$scan.NegativeCandidates,$scan.EdgeCandidates,$UnbiasedTarget,$NegativeTarget,$EdgeTarget)
    if($sel.UnbiasedCount-ne$UnbiasedTarget-or$sel.NegativeCount-ne$NegativeTarget-or$sel.EdgeCount-ne$EdgeTarget){throw "Discovery selection insufficient: unbiased=$($sel.UnbiasedCount), negative=$($sel.NegativeCount), edge=$($sel.EdgeCount)."}
    $selectionPath=Join-Path $OutputRoot 'context-discovery-selection.csv';$mat=[CfaStage3ContextV3.Engine]::Materialize(@($files.FullName),$sel.Selected,$selectionPath,$tempRoot,$effectiveWorkers);if($mat.RowsWritten-ne40000){throw "Materialized $($mat.RowsWritten) selected rows; expected 40000."}
    $readingPath=Join-Path $OutputRoot 'context-discovery-reading.csv';$reading=Build-ReadingPopulation $selectionPath $readingPath $OutputRoot $BatchRows
    $manifestPath=Join-Path $OutputRoot 'context-discovery-batch-manifest.csv';$mw=New-Object System.IO.StreamWriter -ArgumentList $manifestPath,$false,$Utf8;try{Write-CsvRow $mw @('batch_file','rows','bytes','sha256','stratum_counts');foreach($b in $reading.manifest){Write-CsvRow $mw @($b.file,$b.rows,$b.bytes,$b.sha256,$b.stratum_counts)}}finally{$mw.Dispose()}
    $sourceGate=if($scan.TotalRows-eq$ExpectedRows-and$scan.MalformedRows-eq$ExpectedMalformedRows-and$scan.ValidRows-eq$ExpectedValidRows-and$scan.MissingCriticalRows-eq0){'PASS'}else{'FAIL'};$sampleGate=if($sel.UnbiasedCount-eq15000-and$sel.NegativeCount-eq15000-and$sel.EdgeCount-eq10000-and$mat.RowsWritten-eq40000-and$reading.unique_contexts-gt0){'PASS'}else{'FAIL'};$runGate=if($sourceGate-eq'PASS'-and$sampleGate-eq'PASS'){'PASS'}else{'FAIL'}
    $summary=[ordered]@{run_status=$runGate;gates=[ordered]@{'S3-CTX-001'='PASS';'S3-CTX-002'=$sourceGate;'S3-CTX-003'=$sampleGate;'S3-CTX-004'='BLOCKED';'S3-CTX-005'='BLOCKED';'S3-CTX-006'='BLOCKED';'S3-CTX-007'='BLOCKED';'S3-CTX-008'='BLOCKED'};execution=[ordered]@{implementation='CFA_STAGE3_CONTEXT_V3_BOUNDED_TWO_PASS';logical_processor_count=$scan.LogicalProcessorCount;worker_count=$scan.WorkerCount;pass1_elapsed_seconds=[math]::Round($scan.ElapsedSeconds,3);pass1_rows_per_second=[math]::Round($scan.RowsPerSecond,2);materialization_elapsed_seconds=[math]::Round($mat.ElapsedSeconds,3);output_free_gb_before=$freeBefore;minimum_free_gb=$MinFreeGB};source=[ordered]@{archive_files=$files.Count;archives_processed=$scan.ArchivesProcessed;rows_scanned=$scan.TotalRows;malformed_field_count_rows=$scan.MalformedRows;missing_critical_rows=$scan.MissingCriticalRows;valid_context_rows=$scan.ValidRows};context=[ordered]@{schema_version=$ContextSchemaVersion;global_context_cardinality_status='NOT_APPLICABLE';selected_unique_context_sha256=$reading.unique_contexts;selected_repeated_occurrences=(40000-$reading.unique_contexts);replacement_present_rows=$scan.ReplacementRows;blank_page_title_rows=$scan.BlankTitleRows;blank_themes_rows=$scan.BlankThemesRows;blank_persons_rows=$scan.BlankPersonsRows;blank_organizations_rows=$scan.BlankOrganizationsRows;blank_all_names_rows=$scan.BlankAllNamesRows;blank_source_rows=$scan.BlankSourceRows};discovery=[ordered]@{sampling_schema_version=$SamplingSchemaVersion;provisional_candidate_rows=$scan.DiscoveryCandidates;provisional_negative_rows=$scan.DiscoveryNegatives;unbiased_key_candidates=$scan.UnbiasedCandidates.Count;negative_key_candidates=$scan.NegativeCandidates.Count;edge_key_candidates=$scan.EdgeCandidates.Count;selected_unbiased=$sel.UnbiasedCount;selected_retrieval_negative=$sel.NegativeCount;selected_asset_edge=$sel.EdgeCount;selected_source_rows=40000;selected_unique_reading_contexts=$reading.unique_contexts;batch_rows=$BatchRows;batch_files=$reading.manifest.Count};outputs=[ordered]@{discovery_selection=$selectionPath;discovery_selection_sha256=(Get-FileHash $selectionPath -Algorithm SHA256).Hash.ToLowerInvariant();discovery_reading=$readingPath;discovery_reading_sha256=(Get-FileHash $readingPath -Algorithm SHA256).Hash.ToLowerInvariant();batch_manifest=$manifestPath;batch_manifest_sha256=(Get-FileHash $manifestPath -Algorithm SHA256).Hash.ToLowerInvariant();candidate_alias_registry_sha256=(Get-FileHash $aliasPath -Algorithm SHA256).Hash.ToLowerInvariant()}}
    Write-Utf8NoBom (Join-Path $OutputRoot 'context-inventory-summary.json') (($summary|ConvertTo-Json -Depth 10)+[Environment]::NewLine)
    Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host 'CFA STAGE 3 CONTEXT INVENTORY V3: COMPLETE';Write-Host ('Evidence directory: '+$OutputRoot);Write-Host ('Rows scanned: '+$scan.TotalRows+' | rows/sec='+[math]::Round($scan.RowsPerSecond,2));Write-Host ('Selected source rows: 40000 | unique contexts='+$reading.unique_contexts);Write-Host ('S3-CTX-002: '+$sourceGate);Write-Host ('S3-CTX-003: '+$sampleGate);if($runGate-ne'PASS'){exit 2};exit 0
}catch{Write-Host 'CFA STAGE 3 CONTEXT INVENTORY V3: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
