#requires -Version 5.1
[CmdletBinding()]
param([string]$ArchiveRoot='',[string]$OutputRoot='',[ValidateRange(10,5000)][int]$RowsPerArchive=500,[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

function Get-LineMetrics{
 param([System.IO.Stream]$Stream,[int]$MaxRows)
 $counts=@{};$sampled=0;$valid=0;$invalid=0;$crlf=0;$lf=0;$max=0;$utf8=New-Object System.Text.UTF8Encoding($false,$true);$buf=New-Object System.Collections.Generic.List[byte]
 while($sampled-lt$MaxRows){$v=$Stream.ReadByte();if($v-lt0){break};$b=[byte]$v;if($b-eq10){$bytes=$buf.ToArray();$buf.Clear();$sampled++;if($bytes.Length-gt$max){$max=$bytes.Length};$end=$bytes.Length;if($end-gt0-and$bytes[$end-1]-eq13){$crlf++;$end--}else{$lf++};$tabs=0;for($i=0;$i-lt$end;$i++){if($bytes[$i]-eq9){$tabs++}};$fields=$tabs+1;if(-not$counts.ContainsKey($fields)){$counts[$fields]=0};$counts[$fields]=[int]$counts[$fields]+1;try{[void]$utf8.GetString($bytes,0,$end);$valid++}catch{$invalid++}}else{$buf.Add($b)}}
 if($sampled-lt$MaxRows-and$buf.Count-gt0){$bytes=$buf.ToArray();$sampled++;if($bytes.Length-gt$max){$max=$bytes.Length};$tabs=0;for($i=0;$i-lt$bytes.Length;$i++){if($bytes[$i]-eq9){$tabs++}};$fields=$tabs+1;if(-not$counts.ContainsKey($fields)){$counts[$fields]=0};$counts[$fields]=[int]$counts[$fields]+1;try{[void]$utf8.GetString($bytes);$valid++}catch{$invalid++}}
 return [pscustomobject]@{sampled_rows=$sampled;field_counts=$counts;utf8_valid_rows=$valid;utf8_invalid_rows=$invalid;crlf_rows=$crlf;lf_only_rows=$lf;max_line_bytes=$max}
}

function Inspect-Archives{
 param([string[]]$Paths,[int]$Rows)
 $archiveRows=@();$dist=@();foreach($path in $Paths){$f=Get-Item $path;$zip=$null;try{$zip=[System.IO.Compression.ZipFile]::OpenRead($f.FullName);$entries=@($zip.Entries|Where-Object{-not[string]::IsNullOrWhiteSpace($_.Name)});if($entries.Count-lt1){throw "ZIP contains no file entries: $($f.Name)"};$entry=$entries[0];$s=$entry.Open();try{$m=Get-LineMetrics $s $Rows}finally{$s.Dispose()};$keys=@($m.field_counts.Keys|Sort-Object{[int]$_});foreach($k in $keys){$dist+=[pscustomobject]@{archive_file=$f.Name;entry_name=$entry.FullName;field_count=[int]$k;sampled_rows=[int]$m.field_counts[$k]}};$key=[regex]::Match($f.Name,'^(\d{14})').Groups[1].Value;$archiveRows+=[pscustomobject]@{object_key=$key;archive_file=$f.Name;archive_sha256=(Get-FileHash $f.FullName -Algorithm SHA256).Hash.ToLowerInvariant();archive_bytes=[long]$f.Length;zip_entry_count=$entries.Count;inspected_entry=$entry.FullName;entry_uncompressed_bytes=[long]$entry.Length;entry_compressed_bytes=[long]$entry.CompressedLength;sampled_rows=[int]$m.sampled_rows;distinct_field_counts=($keys-join'|');min_field_count=if($keys.Count){[int]$keys[0]}else{0};max_field_count=if($keys.Count){[int]$keys[$keys.Count-1]}else{0};utf8_valid_rows=[int]$m.utf8_valid_rows;utf8_invalid_rows=[int]$m.utf8_invalid_rows;crlf_rows=[int]$m.crlf_rows;lf_only_rows=[int]$m.lf_only_rows;max_line_bytes=[int]$m.max_line_bytes}}finally{if($null-ne$zip){$zip.Dispose()}}};return[pscustomobject]@{archives=$archiveRows;distribution=$dist}
}

function Invoke-SelfTest{$root=Join-Path([System.IO.Path]::GetTempPath())('cfa-gkg-structure-'+[guid]::NewGuid().ToString('N'));try{New-Item -ItemType Directory -Path $root -Force|Out-Null;$paths=@();foreach($key in @('20250401000000','20250515000000','20250630234500')){$p=Join-Path $root($key+'.gkg.csv.zip');$paths+=$p;$z=[System.IO.Compression.ZipFile]::Open($p,[System.IO.Compression.ZipArchiveMode]::Create);try{$e=$z.CreateEntry('sample.gkg.csv');$w=New-Object System.IO.StreamWriter($e.Open(),(New-Object System.Text.UTF8Encoding($false)));try{$w.Write("a`t1`tx`n"+"b`t2`ty`n")}finally{$w.Dispose()}}finally{$z.Dispose()}};$r=Inspect-Archives $paths 10;if($r.archives.Count-ne3){throw'archive count'};if(@($r.archives|Where-Object{$_.min_field_count-ne3-or$_.max_field_count-ne3}).Count-ne0){throw'field count'};if(@($r.archives|Where-Object{$_.utf8_invalid_rows-ne0}).Count-ne0){throw'utf8'};Write-Host 'SELF-TEST: PASS'}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;exit 1}}

try{$docs=[Environment]::GetFolderPath('MyDocuments');if([string]::IsNullOrWhiteSpace($ArchiveRoot)){$ArchiveRoot=Join-Path $docs 'CFA-local\gdelt-gkg-q2-2025'};if([string]::IsNullOrWhiteSpace($OutputRoot)){$OutputRoot=Join-Path $docs 'CFA-local\gdelt-gkg-structure'};$ArchiveRoot=(Resolve-Path $ArchiveRoot).ProviderPath;if(-not(Test-Path $OutputRoot -PathType Container)){New-Item -ItemType Directory -Path $OutputRoot -Force|Out-Null};$files=@(Get-ChildItem $ArchiveRoot -Recurse -File -Filter '*.gkg.csv.zip'|Where-Object{$_.Name-match'^\d{14}\.gkg\.csv\.zip$'}|Sort-Object Name);if($files.Count-lt3){throw "At least three downloaded GKG archives required; observed $($files.Count)."};$idx=@(0,[int][Math]::Floor(($files.Count-1)/2),$files.Count-1)|Sort-Object -Unique;$selected=@();foreach($i in $idx){$selected+=$files[$i].FullName};if($selected.Count-ne3){throw'Could not select three distinct archives.'};$r=Inspect-Archives $selected $RowsPerArchive;$run=(Get-Date -Format'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N');$dir=Join-Path $OutputRoot $run;New-Item -ItemType Directory -Path $dir -Force|Out-Null;$r.archives|Export-Csv(Join-Path $dir 'archive-structure.csv')-NoTypeInformation -Encoding UTF8;$r.distribution|Export-Csv(Join-Path $dir 'field-count-distribution.csv')-NoTypeInformation -Encoding UTF8;$sum=0;$bad=0;foreach($a in $r.archives){$sum+=[int]$a.sampled_rows;$bad+=[int]$a.utf8_invalid_rows};@([pscustomobject]@{run_id=$run;downloaded_archive_files=$files.Count;selected_archives=$selected.Count;rows_per_archive_limit=$RowsPerArchive;total_sampled_rows=$sum;total_utf8_invalid_rows=$bad})|Export-Csv(Join-Path $dir 'inspection-summary.csv')-NoTypeInformation -Encoding UTF8;Write-Host "Evidence directory: $dir";$r.archives|Format-Table object_key,sampled_rows,min_field_count,max_field_count,utf8_valid_rows,utf8_invalid_rows -AutoSize;Write-Host 'CFA GDELT GKG STRUCTURE INSPECTION: PASS'}catch{Write-Host 'CFA GDELT GKG STRUCTURE INSPECTION: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
