#requires -Version 5.1
[CmdletBinding()]
param([string]$RepoRoot='',[string]$EvidenceRoot='',[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

function Write-Utf8NoBom{param([string]$Path,[string]$Content);$p=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $p -PathType Container)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$e=New-Object System.Text.UTF8Encoding($false);[System.IO.File]::WriteAllText($Path,$Content,$e)}
function Get-LatestRun{param([string]$Parent);if(-not(Test-Path -LiteralPath $Parent -PathType Container)){throw "Alias recovery root missing: $Parent"};$runs=@(Get-ChildItem -LiteralPath $Parent -Directory -Force|Sort-Object Name -Descending);foreach($run in $runs){if(Test-Path -LiteralPath (Join-Path $run.FullName 'recovery-summary.csv') -PathType Leaf){return $run}};throw "No usable alias recovery run under: $Parent"}
function Require-File{param([System.IO.DirectoryInfo]$Run,[string]$Name);$p=Join-Path $Run.FullName $Name;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Required alias recovery file missing: $Name"};return $p}
function Get-Text{param([string]$Path);$t=[System.IO.File]::ReadAllText($Path);if($t.Length-gt0-and[int][char]$t[0]-eq0xFEFF){$t=$t.Substring(1)};return $t.TrimEnd("`r","`n")}

function Write-Receipt{
 param([string]$RepoRootPath,[string]$EvidenceRootPath)
 $run=Get-LatestRun (Join-Path $EvidenceRootPath 'gdelt-alias-recovery')
 $summaryPath=Require-File $run 'recovery-summary.csv';$aliasPath=Require-File $run 'alias-recovery.csv';$samplesPath=Require-File $run 'alias-recovery-samples.csv';$quarantinePath=Require-File $run 'quarantine-rows.csv';$archivePath=Require-File $run 'archive-scan.csv'
 $summary=@(Import-Csv $summaryPath);$aliases=@(Import-Csv $aliasPath);$samples=@(Import-Csv $samplesPath);$quarantine=@(Import-Csv $quarantinePath)
 if($summary.Count-ne1){throw 'Alias recovery summary cardinality must be 1.'};if($aliases.Count-ne45){throw "Alias recovery rows must be 45; observed $($aliases.Count)."};if([int]$summary[0].archive_files-ne7163){throw 'Alias recovery archive count must be 7163.'};if([long]$summary[0].quarantined_rows-ne[long]$summary[0].expected_quarantined_rows){throw 'Alias recovery quarantine count mismatch.'}
 $aliasOut=Join-Path $RepoRootPath 'docs\evidence\stage2-alias-recovery.csv';$sampleOut=Join-Path $RepoRootPath 'docs\evidence\stage2-alias-recovery-samples.csv';$quarantineOut=Join-Path $RepoRootPath 'docs\evidence\stage2-alias-quarantine.csv'
 $aliases|Sort-Object base_asset_id,alias_text|Export-Csv -LiteralPath $aliasOut -NoTypeInformation -Encoding UTF8;$samples|Sort-Object base_asset_id,alias_text,date_utc|Export-Csv -LiteralPath $sampleOut -NoTypeInformation -Encoding UTF8;$quarantine|Sort-Object archive_file,row_ordinal|Export-Csv -LiteralPath $quarantineOut -NoTypeInformation -Encoding UTF8
 $b=New-Object System.Text.StringBuilder;[void]$b.AppendLine('# CFA Stage 2 Alias Recovery Evidence');[void]$b.AppendLine('');[void]$b.AppendLine('Recovered alias-observation audit using the byte-diagnostic contract. Non-27-field rows are quarantined and do not contribute to matching. UTF-8 replacement is permitted only in noncritical fields after the prior diagnostic established zero invalid bytes in ALLNAMES and all critical identity/time/source fields.');[void]$b.AppendLine('');[void]$b.AppendLine('- Recovery run: '+$run.Name);[void]$b.AppendLine('- Source diagnostic run: '+[string]$summary[0].source_diagnostic_run);[void]$b.AppendLine('- Archives scanned: '+[string]$summary[0].archive_files);[void]$b.AppendLine('- Rows scanned: '+[string]$summary[0].rows_scanned);[void]$b.AppendLine('- Quarantined rows: '+[string]$summary[0].quarantined_rows);[void]$b.AppendLine('- Observed aliases: '+[string]$summary[0].observed_aliases+' / 45');[void]$b.AppendLine('- Matching surfaces: '+[string]$summary[0].matching_surfaces);[void]$b.AppendLine('');[void]$b.AppendLine('## Recovery summary');[void]$b.AppendLine('');[void]$b.AppendLine('```csv');[void]$b.AppendLine((Get-Text $summaryPath));[void]$b.AppendLine('```');[void]$b.AppendLine('');[void]$b.AppendLine('The normalized 45-row audit, bounded samples, and the complete bounded quarantine list are published separately. The full per-archive scan remains local; its SHA-256 is recorded below. Observations remain evidence for alias review and do not themselves approve context-sensitive aliases.');[void]$b.AppendLine('');foreach($p in @($summaryPath,$aliasPath,$samplesPath,$quarantinePath,$archivePath)){[void]$b.AppendLine('- '+[System.IO.Path]::GetFileName($p)+' SHA-256: '+(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant())}
 $mdOut=Join-Path $RepoRootPath 'docs\evidence\stage2-alias-recovery.md';Write-Utf8NoBom $mdOut $b.ToString();return [pscustomobject]@{run_id=$run.Name;md_path=$mdOut;alias_path=$aliasOut;sample_path=$sampleOut;quarantine_path=$quarantineOut;summary=$summary[0]}
}

function Invoke-SelfTest{
 $root=Join-Path([System.IO.Path]::GetTempPath())('cfa-alias-recovery-pub-'+[guid]::NewGuid().ToString('N'));try{$e=Join-Path $root 'CFA-local\gdelt-alias-recovery\20260101-test';$r=Join-Path $root 'repo';New-Item -ItemType Directory -Path $e -Force|Out-Null;New-Item -ItemType Directory -Path (Join-Path $r 'docs\evidence') -Force|Out-Null;Write-Utf8NoBom (Join-Path $e 'recovery-summary.csv') "run_id,source_diagnostic_run,archive_files,rows_scanned,quarantined_rows,expected_quarantined_rows,observed_aliases,matching_surfaces`n20260101-test,diag,7163,10,5,5,40,ALLNAMES|PAGE_TITLE`n";$rows=@();for($i=1;$i-le45;$i++){$rows+=[pscustomobject]@{base_asset_id=('A'+$i);alias_text=('Alias '+$i);any_surface_document_count=1}};$rows|Export-Csv (Join-Path $e 'alias-recovery.csv') -NoTypeInformation -Encoding UTF8;@([pscustomobject]@{base_asset_id='A1';alias_text='Alias 1';date_utc='20250101'})|Export-Csv (Join-Path $e 'alias-recovery-samples.csv') -NoTypeInformation -Encoding UTF8;@([pscustomobject]@{archive_file='a';row_ordinal=1;observed_field_count=1;reject_reason='RAW_FIELD_COUNT_NOT_27'})|Export-Csv (Join-Path $e 'quarantine-rows.csv') -NoTypeInformation -Encoding UTF8;Write-Utf8NoBom (Join-Path $e 'archive-scan.csv') "archive_file,rows_scanned`na,1`n";$x=Write-Receipt $r (Join-Path $root 'CFA-local');if(-not(Test-Path $x.md_path)){throw 'receipt missing'};if(-not(Test-Path $x.alias_path)){throw 'alias output missing'};$t=[System.IO.File]::ReadAllText($x.md_path);if(-not$t.Contains('20260101-test')){throw 'run id missing'};if($t.Contains($root)){throw 'path leak'};Write-Host 'SELF-TEST: PASS'}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}}
try{if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};if([string]::IsNullOrWhiteSpace($EvidenceRoot)){$EvidenceRoot=Join-Path([Environment]::GetFolderPath('MyDocuments'))'CFA-local'};$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).ProviderPath;$EvidenceRoot=(Resolve-Path -LiteralPath $EvidenceRoot).ProviderPath;$x=Write-Receipt $RepoRoot $EvidenceRoot;Write-Host ('Alias recovery run: '+$x.run_id);Write-Host ('Rows scanned: '+[string]$x.summary.rows_scanned);Write-Host ('Quarantined rows: '+[string]$x.summary.quarantined_rows);Write-Host ('Observed aliases: '+[string]$x.summary.observed_aliases+' / 45');Write-Host 'CFA STAGE 2 ALIAS RECOVERY PUBLISH: PASS'}catch{Write-Host 'CFA STAGE 2 ALIAS RECOVERY PUBLISH: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
