#requires -Version 5.1
[CmdletBinding()]
param([string]$EvidenceRoot='',[string]$RepoRoot='',[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

function Write-Utf8NoBom{param([string]$Path,[string]$Content);$p=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $p -PathType Container)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$e=New-Object System.Text.UTF8Encoding($false);[System.IO.File]::WriteAllText($Path,$Content,$e)}
function Get-LatestRun{param([string]$Parent,[switch]$Optional);if(-not(Test-Path -LiteralPath $Parent -PathType Container)){if($Optional){return $null};throw "Evidence directory missing: $Parent"};$r=@(Get-ChildItem -LiteralPath $Parent -Directory -Force|Sort-Object Name -Descending);if($r.Count -eq 0){if($Optional){return $null};throw "No evidence runs under: $Parent"};return $r[0]}
function Require-File{param([System.IO.DirectoryInfo]$Run,[string]$Name);$p=Join-Path $Run.FullName $Name;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Required evidence missing from $($Run.Name): $Name"};return $p}
function Get-Text{param([string]$Path);$t=[System.IO.File]::ReadAllText($Path);if($t.Length -gt 0 -and [int][char]$t[0]-eq 0xFEFF){$t=$t.Substring(1)};return $t.TrimEnd("`r","`n")}
function Count-Decision{param([object[]]$Rows,[string]$Decision);return @($Rows|Where-Object{[string]$_.cfa_independent_review_decision -eq $Decision}).Count}

function Write-Stage2Receipt{
 param([string]$EvidenceRootPath,[string]$RepoRootPath)
 $cg=Get-LatestRun -Parent (Join-Path $EvidenceRootPath 'coingecko-identity')
 $structure=Get-LatestRun -Parent (Join-Path $EvidenceRootPath 'gdelt-gkg-structure') -Optional
 $summaryPath=Require-File $cg 'run-summary.csv';$sourcePath=Require-File $cg 'source-files.csv';$bridgePath=Require-File $cg 'mapping-bridge-evidence.csv'
 $summary=@(Import-Csv $summaryPath);$sources=@(Import-Csv $sourcePath);$bridges=@(Import-Csv $bridgePath)
 if($summary.Count-ne1){throw 'CoinGecko run summary cardinality must be 1.'};if($bridges.Count-ne435){throw "Bridge rows must be 435; observed $($bridges.Count)."};if([int]$summary[0].candidate_assets-ne435){throw 'candidate_assets must be 435.'};if($sources.Count-lt2){throw 'CoinGecko source manifest is too small.'}
 $allowed=@('APPROVE_CURRENT_KRAKEN_PAIR_BRIDGE','UNVERIFIED_MULTIPLE_KRAKEN_PAIR_BRIDGES','UNVERIFIED_NO_CURRENT_KRAKEN_PAIR_BRIDGE');if(@($bridges|Where-Object{$allowed-notcontains[string]$_.cfa_independent_review_decision}).Count-gt0){throw 'Unsupported bridge decision.'}
 foreach($s in $sources){if([string]$s.sha256-notmatch'^[0-9a-f]{64}$'){throw "Malformed SHA for $($s.file_name)."};if([long]$s.bytes-le0){throw "Invalid bytes for $($s.file_name)."};if([string]::IsNullOrWhiteSpace([string]$s.source_url)){throw "Missing source URL for $($s.file_name)."}}
 $approve=Count-Decision $bridges 'APPROVE_CURRENT_KRAKEN_PAIR_BRIDGE';$multi=Count-Decision $bridges 'UNVERIFIED_MULTIPLE_KRAKEN_PAIR_BRIDGES';$none=Count-Decision $bridges 'UNVERIFIED_NO_CURRENT_KRAKEN_PAIR_BRIDGE';if(($approve+$multi+$none)-ne435){throw 'Bridge decision accounting mismatch.'}
 $csvOut=Join-Path $RepoRootPath 'docs\evidence\stage2-coingecko-bridge-evidence.csv';$bridges|Sort-Object base_asset_id|Export-Csv -LiteralPath $csvOut -NoTypeInformation -Encoding UTF8
 $b=New-Object System.Text.StringBuilder;[void]$b.AppendLine('# CFA Stage 2 Local Evidence');[void]$b.AppendLine('');[void]$b.AppendLine('Curated local evidence. Raw CoinGecko JSON and raw GDELT archives remain under Documents\CFA-local and outside Git.');[void]$b.AppendLine('')
 [void]$b.AppendLine('## CoinGecko / Kraken bridge evidence');[void]$b.AppendLine('');[void]$b.AppendLine('- Evidence run: '+$cg.Name);[void]$b.AppendLine('- Candidate assets: 435');[void]$b.AppendLine('- Unique current Kraken pair bridges: '+$approve);[void]$b.AppendLine('- Multiple current Kraken pair bridges: '+$multi);[void]$b.AppendLine('- No current Kraken pair bridge: '+$none);[void]$b.AppendLine('- Raw source files: '+$sources.Count);[void]$b.AppendLine('')
 foreach($section in @(@('Run summary',$summaryPath),@('Raw source file manifest',$sourcePath))){[void]$b.AppendLine('### '+$section[0]);[void]$b.AppendLine('');[void]$b.AppendLine('```csv');[void]$b.AppendLine((Get-Text $section[1]));[void]$b.AppendLine('```');[void]$b.AppendLine('')}
 [void]$b.AppendLine('### CoinGecko local evidence hashes');[void]$b.AppendLine('');[void]$b.AppendLine('| File | SHA-256 |');[void]$b.AppendLine('|---|---|');foreach($p in @($summaryPath,$sourcePath,$bridgePath)){[void]$b.AppendLine('| '+[System.IO.Path]::GetFileName($p)+' | '+(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()+' |')};[void]$b.AppendLine('')
 if($null-ne$structure){$ss=Require-File $structure 'inspection-summary.csv';$as=Require-File $structure 'archive-structure.csv';$fd=Require-File $structure 'field-count-distribution.csv';[void]$b.AppendLine('## CFA GDELT GKG binary-safe structure inspection');[void]$b.AppendLine('');[void]$b.AppendLine('- Evidence run: '+$structure.Name);foreach($section in @(@('Inspection summary',$ss),@('Archive structure',$as),@('Field-count distribution',$fd))){[void]$b.AppendLine('');[void]$b.AppendLine('### '+$section[0]);[void]$b.AppendLine('');[void]$b.AppendLine('```csv');[void]$b.AppendLine((Get-Text $section[1]));[void]$b.AppendLine('```')};[void]$b.AppendLine('');[void]$b.AppendLine('The inspection counts delimiters and validates UTF-8 at the raw-byte row boundary without publishing raw news rows or assigning semantic field meanings.');[void]$b.AppendLine('');foreach($p in @($ss,$as,$fd)){[void]$b.AppendLine('- '+[System.IO.Path]::GetFileName($p)+' SHA-256: '+(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant())}}
 [void]$b.AppendLine('');[void]$b.AppendLine('The normalized 435-asset bridge table is published separately as docs/evidence/stage2-coingecko-bridge-evidence.csv. Unique current pair bridges are independent mapping evidence; alias semantics remain UNVERIFIED until raw-news matching rules are defined and validated.')
 $mdOut=Join-Path $RepoRootPath 'docs\evidence\latest-stage2-local.md';Write-Utf8NoBom $mdOut $b.ToString();return [pscustomobject]@{run_id=$cg.Name;structure_run=if($null-ne$structure){$structure.Name}else{''};receipt_path=$mdOut;bridge_path=$csvOut;approve=$approve;multiple=$multi;no_bridge=$none}
}

function Invoke-SelfTest{
 $root=Join-Path ([System.IO.Path]::GetTempPath()) ('cfa-s2-pub-'+[guid]::NewGuid().ToString('N'));try{$e=Join-Path $root 'CFA-local';$cg=Join-Path $e 'coingecko-identity\20260101-cg';$st=Join-Path $e 'gdelt-gkg-structure\20260101-st';$repo=Join-Path $root 'repo';foreach($d in @($cg,$st,(Join-Path $repo 'docs\evidence'))){New-Item -ItemType Directory -Path $d -Force|Out-Null};Write-Utf8NoBom (Join-Path $cg 'run-summary.csv') "run_id,candidate_assets`n20260101-cg,435`n";Write-Utf8NoBom (Join-Path $cg 'source-files.csv') ("file_name,sha256,bytes,record_count,source_url`na.json,$('a'*64),10,1,https://example.invalid/a`nb.json,$('b'*64),20,1,https://example.invalid/b`n");$rows=@();for($i=1;$i-le435;$i++){$rows+=[pscustomobject]@{base_asset_id=('A{0:D3}'-f$i);cfa_independent_review_decision='APPROVE_CURRENT_KRAKEN_PAIR_BRIDGE'}};$rows|Export-Csv (Join-Path $cg 'mapping-bridge-evidence.csv') -NoTypeInformation -Encoding UTF8;Write-Utf8NoBom (Join-Path $st 'inspection-summary.csv') "run_id,total_sampled_rows`n20260101-st,1500`n";Write-Utf8NoBom (Join-Path $st 'archive-structure.csv') "object_key,sampled_rows`n1,500`n";Write-Utf8NoBom (Join-Path $st 'field-count-distribution.csv') "archive_file,field_count,sampled_rows`na,27,500`n";$r=Write-Stage2Receipt $e $repo;if(-not(Test-Path $r.receipt_path)){throw 'receipt missing'};$t=[System.IO.File]::ReadAllText($r.receipt_path);if(-not$t.Contains('20260101-cg')-or-not$t.Contains('20260101-st')){throw 'receipt content'};if($t.Contains($root)){throw 'path leak'};Write-Host 'SELF-TEST: PASS'}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;exit 1}}
try{if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};if([string]::IsNullOrWhiteSpace($EvidenceRoot)){$EvidenceRoot=Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'CFA-local'};$RepoRoot=(Resolve-Path $RepoRoot).ProviderPath;$EvidenceRoot=(Resolve-Path $EvidenceRoot).ProviderPath;$r=Write-Stage2Receipt $EvidenceRoot $RepoRoot;Write-Host ('Stage 2 CoinGecko run: '+$r.run_id);if($r.structure_run){Write-Host ('GDELT structure run: '+$r.structure_run)};Write-Host ('Unique bridges: '+$r.approve);Write-Host ('Multiple bridges: '+$r.multiple);Write-Host ('No bridge: '+$r.no_bridge);Write-Host 'CFA STAGE 2 EVIDENCE PUBLISH: PASS'}catch{Write-Host 'CFA STAGE 2 EVIDENCE PUBLISH: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
