#requires -Version 5.1
[CmdletBinding()]
param([string]$RepoRoot='',[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Assert-Stage1Pass{param([string]$Root);$p=Join-Path $Root 'docs\stage1-validation-status.md';if(-not(Test-Path $p)){throw 'Stage 1 status receipt missing.'};$t=[System.IO.File]::ReadAllText($p);foreach($g in @('CFA-S1-009','CFA-S1-010')){$pat='\|\s*'+[regex]::Escape($g)+'[^|]*\|\s*PASS\s*\|';if($t-notmatch$pat){throw "Stage 1 prerequisite not PASS: $g"}}}
function Assert-Stage2StructuralPass{param([string]$Root);$p=Join-Path $Root 'docs\evidence\stage2-identity-review.json';if(-not(Test-Path $p)){throw 'Stage 2 structural review missing.'};$o=Get-Content $p -Raw|ConvertFrom-Json;foreach($g in @('CFA-S2-001','CFA-S2-002','CFA-S2-004')){$m=@($o.gates|Where-Object{[string]$_.gate_id-eq$g});if($m.Count-ne1-or[string]$m[0].status-ne'PASS'){throw "Stage 2 structural prerequisite not PASS: $g"}}}
function Invoke-Child{param([string]$Path,[string[]]$Arguments);if(-not(Test-Path $Path)){throw "Missing child script: $Path"};& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Path @Arguments;if($LASTEXITCODE-ne0){throw ('Child failed '+$LASTEXITCODE+': '+$Path)}}
function Invoke-SelfTest{$root=Join-Path ([System.IO.Path]::GetTempPath()) ('cfa-s2-run-'+[guid]::NewGuid().ToString('N'));try{New-Item -ItemType Directory -Path (Join-Path $root 'docs\evidence') -Force|Out-Null;[System.IO.File]::WriteAllText((Join-Path $root 'docs\stage1-validation-status.md'),"| Gate | Status |`n|---|---|`n| CFA-S1-009 Advance | PASS |`n| CFA-S1-010 News | PASS |`n");$j=[ordered]@{gates=@([pscustomobject]@{gate_id='CFA-S2-001';status='PASS'},[pscustomobject]@{gate_id='CFA-S2-002';status='PASS'},[pscustomobject]@{gate_id='CFA-S2-004';status='PASS'})}|ConvertTo-Json -Depth 5;[System.IO.File]::WriteAllText((Join-Path $root 'docs\evidence\stage2-identity-review.json'),$j);Assert-Stage1Pass $root;Assert-Stage2StructuralPass $root;Write-Host 'SELF-TEST: PASS'}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;exit 1}}
try{if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};$RepoRoot=(Resolve-Path $RepoRoot).ProviderPath;Assert-Stage1Pass $RepoRoot;Assert-Stage2StructuralPass $RepoRoot;Write-Host 'Stage 1 prerequisite: PASS';Write-Host 'Stage 2 structural prerequisites CFA-S2-001/002/004: PASS';Invoke-Child (Join-Path $RepoRoot 'scripts\windows\Acquire-CfaCoinGeckoIdentityEvidence.ps1') @('-RepoRoot',$RepoRoot);Invoke-Child (Join-Path $RepoRoot 'scripts\windows\Inspect-CfaGdeltGkgStructure.ps1') @();Invoke-Child (Join-Path $RepoRoot 'scripts\windows\Sync-CfaStage2Evidence.ps1') @('-RepoRoot',$RepoRoot);Write-Host '';Write-Host '=== CFA STAGE 2 EVIDENCE STATUS ===';Write-Host 'CFA-S2-001 Eligible Kraken base-asset universe reconciliation : PASS';Write-Host 'CFA-S2-002 CoinGecko candidate-file structural integrity      : PASS';Write-Host 'CFA-S2-004 Alias seed structural linkage                     : PASS';Write-Host 'CFA-S2-003 CoinGecko mapping decisions                       : REVIEW_REQUIRED';Write-Host 'CFA-S2-005 Alias semantic validation                         : UNVERIFIED';Write-Host 'CFA-S2-006 Advance to news matching definition               : BLOCKED';Write-Host 'CoinGecko/Kraken bridge evidence and binary-safe GDELT structure evidence are published for repository review.'}catch{Write-Host 'CFA STAGE 2 RUNNER: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
