#requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$Stage7ValidationReceiptPath,[string]$RepoRoot='',[string]$OutputRoot='',[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Invariant=[Globalization.CultureInfo]::InvariantCulture
$ExpectedStage7ValidationReceiptSha='e3e9088e511b74e875e1bccc3e8d292acc9c49209c93943117195f8ace5b3756'
$ExpectedModelSha='fc0498881957688acffd6fe3805ac96037ca884304bff9964e1e248b4ec0e024'
$ExpectedSplitSha='4a0878a60ba16dfaddc10591931ec4c659efe7c04415338805f660a998625874'
$ExpectedEmbargoSha='d938a382a4a8bb654d07d678fcebfe887a32933b0c1c5195104f38e3017c4fdd'
$ExpectedPreprocessSha='8a2a02676236b31d05dbdba6e11f8cd4f4086973448958337e0ee50c52329578'
$ExpectedBenchmarkSha='9b2fd8c9deae62b7c8bf1e04df6ec4d8926844fb8becd995e1efacb927399f9c'
$ExpectedValidationChecksSha='e591ca703ce68dd5b6d92c9dc770da57d042ec1a3462591473ec2737a98a6cef'
$FactorIds=@('MKT_RET_USD_UTC_DAY_OBS_L1','MKT_RANGE_LOG_UTC_DAY_L1','MKT_OBS_COUNT_UTC_DAY_L1','MKT_OBS_SPAN_MIN_UTC_DAY_L1','NEWS_V6_MATCH_COUNT_24H_LAG15','NEWS_V6_MATCH_COUNT_6H_LAG15','NEWS_V6_SOURCE_COUNT_24H_LAG15')
if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).ProviderPath
. (Join-Path $PSScriptRoot 'CfaStage8PlsCore.ps1');. (Join-Path $PSScriptRoot 'CfaStage8PlsData.ps1')

function Assert-CfaStage8Entry {
    param($S7,[string]$ModelPath,[string]$SplitPath,[string]$EmbargoPath,[string]$PrePath,[string]$BenchPath,[string]$ChecksPath)
    $s7Contract=Get-Content -LiteralPath (Require-CfaFile (Join-Path $RepoRoot 'docs\evidence\stage7-model-ready-contract.md') 'Stage 7 contract') -Raw
    if($s7Contract-notmatch'CFA-S7-008_PASS'-or$s7Contract-notmatch'STAGE7_FROZEN'){throw 'Stage 7 repository freeze marker missing.'}
    if([string]$S7.status-ne'PASS'-or[string]$S7.stage-ne'CFA_STAGE_7'-or[string]$S7.validation-ne'INDEPENDENT_MODEL_READY_V1'){throw 'Stage 7 validation receipt identity mismatch.'}
    if((Get-CfaSha $ModelPath)-ne$ExpectedModelSha-or(Get-CfaSha $SplitPath)-ne$ExpectedSplitSha-or(Get-CfaSha $EmbargoPath)-ne$ExpectedEmbargoSha-or(Get-CfaSha $PrePath)-ne$ExpectedPreprocessSha-or(Get-CfaSha $BenchPath)-ne$ExpectedBenchmarkSha-or(Get-CfaSha $ChecksPath)-ne$ExpectedValidationChecksSha){throw 'Frozen Stage 7 output hash mismatch.'}
}

function Write-CfaPredictionCsv {
    param([object[]]$Rows,[double[]]$Pls,[hashtable]$Bench,[string]$Path)
    $out=New-Object System.Collections.ArrayList
    for($i=0;$i-lt$Rows.Count;$i++){[void]$out.Add([pscustomobject][ordered]@{base_asset_id=$Rows[$i].base_asset_id;response_day_utc=$Rows[$i].response_day_utc;actual_response=$Rows[$i].response_value_log_return;pls_prediction=$Pls[$i].ToString('R',$Invariant);bench_zero_return=$Bench.BENCH_ZERO_RETURN[$i].ToString('R',$Invariant);bench_prior_market_return=$Bench.BENCH_PRIOR_MARKET_RETURN[$i].ToString('R',$Invariant);bench_response_mean=$Bench.BENCH_RESPONSE_MEAN[$i].ToString('R',$Invariant)})}
    @($out.ToArray())|Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

if($SelfTest){try{if(-not(Test-CfaStage8PlsCore)){throw 'PLS core self-test returned false.'};Write-Host 'SELF-TEST: PASS';exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}}

try{
    $stage8Contract=Get-Content -LiteralPath (Require-CfaFile (Join-Path $RepoRoot 'docs\evidence\stage8-pls-contract.md') 'Stage 8 contract') -Raw
    foreach($m in @('PLS1/NIPALS','components 1 through 7','LOWEST_VALIDATION_RMSE','BENCH_ZERO_RETURN','CFA-S8-007')){if($stage8Contract-notmatch[regex]::Escape($m)){throw "Stage 8 contract marker missing: $m"}}
    $Stage7ValidationReceiptPath=Require-CfaFile $Stage7ValidationReceiptPath 'Stage 7 independent validation receipt';if((Get-CfaSha $Stage7ValidationReceiptPath)-ne$ExpectedStage7ValidationReceiptSha){throw 'Stage 7 validation receipt hash mismatch.'}
    $s7=Get-Content -LiteralPath $Stage7ValidationReceiptPath -Raw|ConvertFrom-Json
    $modelPath=Require-CfaFile ([string]$s7.outputs.model_ready) 'Model-ready CSV';$splitPath=Require-CfaFile ([string]$s7.outputs.split_assignment) 'Split assignment';$embargoPath=Require-CfaFile ([string]$s7.outputs.embargo_exclusions) 'Embargo exclusions';$prePath=Require-CfaFile ([string]$s7.outputs.preprocessing_parameters) 'Preprocessing parameters';$benchPath=Require-CfaFile ([string]$s7.outputs.benchmark_plan) 'Benchmark plan';$checksPath=Require-CfaFile ([string]$s7.outputs.validation_checks) 'Stage 7 validation checks'
    Assert-CfaStage8Entry $s7 $modelPath $splitPath $embargoPath $prePath $benchPath $checksPath
    $model=@(Import-Csv -LiteralPath $modelPath);if($model.Count-ne26337){throw 'Model-ready row count mismatch.'};$train=@($model|Where-Object{$_.design_role-eq'TRAIN'});$val=@($model|Where-Object{$_.design_role-eq'VALIDATION'});$test=@($model|Where-Object{$_.design_role-eq'TEST'});if($train.Count-ne15648-or$val.Count-ne5323-or$test.Count-ne5366){throw 'Frozen role row count mismatch.'}
    $preMap=Get-CfaPreprocessMap @(Import-Csv -LiteralPath $prePath);$benchPlan=Get-Content -LiteralPath $benchPath -Raw|ConvertFrom-Json;if([string]$benchPlan.component_selection.criterion-ne'LOWEST_VALIDATION_RMSE'-or[string]$benchPlan.component_selection.tie_break-ne'SMALLER_COMPONENT_COUNT'-or-not[bool]$benchPlan.component_selection.test_metrics_forbidden){throw 'Frozen selection rule mismatch.'}

    # VALIDATION sweep only: TEST is untouched until selected component count is fixed.
    $trainP=Build-CfaProcessed $train $preMap 'VALIDATION_FIT' $FactorIds;$valP=Build-CfaProcessed $val $preMap 'VALIDATION_FIT' $FactorIds;$path=Fit-CfaPls1Path $trainP.X $trainP.y_centered 7
    $compRows=New-Object System.Collections.ArrayList;$valPredByK=@{};$selectedK=0;$bestRmse=[double]::PositiveInfinity
    for($k=1;$k-le7;$k++){$beta=[double[]]$path.betas[$k-1];$pred=Predict-CfaPlsOriginal $valP.X $beta $trainP.response_center;$mm=Get-CfaRegressionMetrics $valP.y_raw $pred $trainP.response_center;$valPredByK[$k]=$pred;[void]$compRows.Add([pscustomobject][ordered]@{components=$k;n=$mm.n;rmse=$mm.rmse.ToString('R',$Invariant);mae=$mm.mae.ToString('R',$Invariant);sse=$mm.sse.ToString('R',$Invariant);predictive_r2_vs_response_mean=$mm.predictive_r2.ToString('R',$Invariant)});if($mm.rmse-lt$bestRmse){$selectedK=$k;$bestRmse=$mm.rmse}}
    if($selectedK-lt1){throw 'Component selection failed.'};$valBeta=[double[]]$path.betas[$selectedK-1];$valPred=[double[]]$valPredByK[$selectedK];$valMetric=Get-CfaRegressionMetrics $valP.y_raw $valPred $trainP.response_center

    # TEST phase begins after selectedK is fixed above.
    $trainVal=@($model|Where-Object{$_.design_role-in@('TRAIN','VALIDATION')});$trainValP=Build-CfaProcessed $trainVal $preMap 'TEST_REFIT' $FactorIds;$testP=Build-CfaProcessed $test $preMap 'TEST_REFIT' $FactorIds;$testPath=Fit-CfaPls1Path $trainValP.X $trainValP.y_centered $selectedK;$testBeta=[double[]]$testPath.betas[$selectedK-1];$testPred=Predict-CfaPlsOriginal $testP.X $testBeta $trainValP.response_center;$testMetric=Get-CfaRegressionMetrics $testP.y_raw $testPred $trainValP.response_center

    $benchRows=New-Object System.Collections.ArrayList;$vBench=@{};$tBench=@{}
    foreach($bid in @('BENCH_ZERO_RETURN','BENCH_PRIOR_MARKET_RETURN','BENCH_RESPONSE_MEAN')){$vp=Get-CfaBenchmarkPred $val $bid $trainP.response_center;$tp=Get-CfaBenchmarkPred $test $bid $trainValP.response_center;$vBench[$bid]=$vp;$tBench[$bid]=$tp;[void]$benchRows.Add((New-CfaMetricRow 'VALIDATION' $bid (Get-CfaRegressionMetrics $valP.y_raw $vp $trainP.response_center)));[void]$benchRows.Add((New-CfaMetricRow 'TEST' $bid (Get-CfaRegressionMetrics $testP.y_raw $tp $trainValP.response_center)))}

    if([string]::IsNullOrWhiteSpace($OutputRoot)){$OutputRoot=Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'CFA-local\stage8-pls'};$runDir=Join-Path $OutputRoot ((Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $runDir -Force|Out-Null
    $compPath=Join-Path $runDir 'stage8-validation-component-metrics.csv';$valPredPath=Join-Path $runDir 'stage8-validation-selected-predictions.csv';$testPredPath=Join-Path $runDir 'stage8-test-selected-predictions.csv';$benchMetricsPath=Join-Path $runDir 'stage8-benchmark-metrics.csv';$coefPath=Join-Path $runDir 'stage8-selected-coefficients.csv';$selectedPath=Join-Path $runDir 'stage8-selected-model.json';$receiptPath=Join-Path $runDir 'stage8-pls-run-receipt.json'
    @($compRows.ToArray())|Export-Csv -LiteralPath $compPath -NoTypeInformation -Encoding UTF8;@($benchRows.ToArray())|Export-Csv -LiteralPath $benchMetricsPath -NoTypeInformation -Encoding UTF8;Write-CfaPredictionCsv $val $valPred $vBench $valPredPath;Write-CfaPredictionCsv $test $testPred $tBench $testPredPath
    $coefRows=New-Object System.Collections.ArrayList;foreach($pi in @([pscustomobject]@{phase='VALIDATION_FIT';beta=$valBeta;center=$trainP.response_center},[pscustomobject]@{phase='TEST_REFIT';beta=$testBeta;center=$trainValP.response_center})){for($j=0;$j-lt$FactorIds.Count;$j++){$id=$FactorIds[$j];$pp=$preMap[$pi.phase+'|'+$id];[void]$coefRows.Add([pscustomobject][ordered]@{phase=$pi.phase;selected_components=$selectedK;variable=$id;beta_preprocessed=([double]$pi.beta[$j]).ToString('R',$Invariant);predictor_center=[string]$pp.center;predictor_scale=[string]$pp.scale;response_center=([double]$pi.center).ToString('R',$Invariant)})}};@($coefRows.ToArray())|Export-Csv -LiteralPath $coefPath -NoTypeInformation -Encoding UTF8
    $selected=[ordered]@{version='CFA_STAGE8_PLS1_NIPALS_V1';selected_components=$selectedK;selection_rule='LOWEST_VALIDATION_RMSE_THEN_SMALLER_COMPONENT_COUNT';component_grid=@(1,2,3,4,5,6,7);test_used_for_selection=$false;validation=[ordered]@{n=$valMetric.n;rmse=$valMetric.rmse;mae=$valMetric.mae;sse=$valMetric.sse;predictive_r2_vs_response_mean=$valMetric.predictive_r2};test=[ordered]@{n=$testMetric.n;rmse=$testMetric.rmse;mae=$testMetric.mae;sse=$testMetric.sse;predictive_r2_vs_response_mean=$testMetric.predictive_r2};algorithm='PLS1_NIPALS_DEFLATION';tolerance=$script:CfaPlsTolerance};[IO.File]::WriteAllText($selectedPath,(($selected|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))
    $receipt=[ordered]@{status='VALIDATION_CANDIDATE';stage='CFA_STAGE_8';run='PLS1_NIPALS_V1';sources=[ordered]@{stage7_validation_receipt=$Stage7ValidationReceiptPath;stage7_validation_receipt_sha256=(Get-CfaSha $Stage7ValidationReceiptPath);model_ready_sha256=(Get-CfaSha $modelPath);preprocessing_parameters_sha256=(Get-CfaSha $prePath);benchmark_plan_sha256=(Get-CfaSha $benchPath)};design=[ordered]@{train_rows=$train.Count;validation_rows=$val.Count;test_rows=$test.Count;component_grid=@(1,2,3,4,5,6,7);selected_components=$selectedK;selection_rule='LOWEST_VALIDATION_RMSE_THEN_SMALLER_COMPONENT_COUNT';test_used_for_selection=$false};outputs=[ordered]@{validation_component_metrics=$compPath;validation_component_metrics_sha256=(Get-CfaSha $compPath);validation_selected_predictions=$valPredPath;validation_selected_predictions_sha256=(Get-CfaSha $valPredPath);test_selected_predictions=$testPredPath;test_selected_predictions_sha256=(Get-CfaSha $testPredPath);benchmark_metrics=$benchMetricsPath;benchmark_metrics_sha256=(Get-CfaSha $benchMetricsPath);selected_coefficients=$coefPath;selected_coefficients_sha256=(Get-CfaSha $coefPath);selected_model=$selectedPath;selected_model_sha256=(Get-CfaSha $selectedPath)};gates=[ordered]@{'CFA-S8-001'='PASS';'CFA-S8-002'='PASS';'CFA-S8-003'='PASS';'CFA-S8-004'='PASS';'CFA-S8-005'='PASS';'CFA-S8-006'='PASS';'CFA-S8-007'='BLOCKED';'CFA-S8-008'='BLOCKED'};next_action='Independently validate exact Stage 8 predictions, metrics, component selection, benchmark outputs and hashes before freeze.'};[IO.File]::WriteAllText($receiptPath,(($receipt|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))
    Write-Host '';Write-Host 'CFA STAGE 8 PLS1/NIPALS RUN: VALIDATION CANDIDATE';Write-Host "TRAIN / VALIDATION / TEST rows: $($train.Count) / $($val.Count) / $($test.Count)";Write-Host 'Component grid: 1..7';Write-Host "Selected components by VALIDATION RMSE: $selectedK";Write-Host "Selected VALIDATION RMSE / MAE / predictive R2: $($valMetric.rmse.ToString('R',$Invariant)) / $($valMetric.mae.ToString('R',$Invariant)) / $($valMetric.predictive_r2.ToString('R',$Invariant))";Write-Host "Selected TEST RMSE / MAE / predictive R2: $($testMetric.rmse.ToString('R',$Invariant)) / $($testMetric.mae.ToString('R',$Invariant)) / $($testMetric.predictive_r2.ToString('R',$Invariant))";Write-Host 'TEST used for component selection: False';Write-Host 'CFA-S8-001 through CFA-S8-006: PASS';Write-Host 'CFA-S8-007 independent validation: BLOCKED';Write-Host 'CFA-S8-008 Stage 8 freeze: BLOCKED';Write-Host "Validation component metrics: $compPath";Write-Host "Benchmark metrics: $benchMetricsPath";Write-Host "Selected model: $selectedPath";Write-Host "Run receipt: $receiptPath";exit 0
}catch{Write-Host '';Write-Host 'CFA STAGE 8 PLS1/NIPALS RUN: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
