#requires -Version 5.1
[CmdletBinding()]
param([string]$RepoRoot='',[switch]$ForceRescan,[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Get-LatestValidRun{param([string]$Parent);if(-not(Test-Path -LiteralPath $Parent -PathType Container)){return $null};foreach($run in @(Get-ChildItem -LiteralPath $Parent -Directory -Force|Sort-Object Name -Descending)){$s=Join-Path $run.FullName 'recovery-summary.csv';$a=Join-Path $run.FullName 'alias-recovery.csv';if((Test-Path $s -PathType Leaf)-and(Test-Path $a -PathType Leaf)){$summary=@(Import-Csv $s);$aliases=@(Import-Csv $a);if($summary.Count-eq1-and$aliases.Count-eq45-and[int]$summary[0].archive_files-eq7163-and[long]$summary[0].quarantined_rows-eq[long]$summary[0].expected_quarantined_rows){return $run}}};return $null}
function Invoke-Child{param([string]$Path,[string[]]$Args);& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Path @Args;$c=$LASTEXITCODE;if($c-ne0){throw "Child failed ${c}: $Path"}}
function Invoke-Recovery{param([string]$Path,[string[]]$Args);& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Path @Args;$c=$LASTEXITCODE;if($c-eq0){return 'PASS'};if($c-eq2){return 'FAIL'};throw "Recovery scan failed ${c}: $Path"}
function Invoke-SelfTest{$root=Join-Path([System.IO.Path]::GetTempPath())('cfa-alias-recovery-run-'+[guid]::NewGuid().ToString('N'));try{$p=Join-Path $root 'gdelt-alias-recovery\20260101-test';New-Item -ItemType Directory -Path $p -Force|Out-Null;[System.IO.File]::WriteAllText((Join-Path $p 'recovery-summary.csv'),"archive_files,quarantined_rows,expected_quarantined_rows`n7163,5,5`n");$rows=@();for($i=1;$i-le45;$i++){$rows+=[pscustomobject]@{base_asset_id=('A'+$i)}};$rows|Export-Csv (Join-Path $p 'alias-recovery.csv') -NoTypeInformation;$r=Get-LatestValidRun (Join-Path $root 'gdelt-alias-recovery');if($null-eq$r-or$r.Name-ne'20260101-test'){throw 'reuse detection'};Write-Host 'SELF-TEST: PASS'}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;exit 1}}
try{if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).ProviderPath;$parent=Join-Path([Environment]::GetFolderPath('MyDocuments'))'CFA-local\gdelt-alias-recovery';$run=$null;$gate='UNVERIFIED';if(-not$ForceRescan){$run=Get-LatestValidRun $parent};if($null-ne$run){Write-Host ('Reusing completed alias recovery evidence: '+$run.Name);$gate='PASS'}else{$gate=Invoke-Recovery (Join-Path $RepoRoot 'scripts\windows\Recover-CfaStage2AliasObservations.ps1') @('-RepoRoot',$RepoRoot)};if($gate-ne'PASS'){throw 'Alias recovery parser/quarantine gate is not PASS.'};Invoke-Child (Join-Path $RepoRoot 'scripts\windows\Sync-CfaStage2AliasRecovery.ps1') @('-RepoRoot',$RepoRoot);Write-Host '';Write-Host '=== CFA STAGE 2 ALIAS RECOVERY STATUS ===';Write-Host ('Recovered parser/quarantine gate : '+$gate);Write-Host 'Alias semantic validation        : REVIEW_REQUIRED';Write-Host 'Reason: multi-surface observation evidence is published; context-sensitive aliases still require semantic review.';Write-Host 'CFA STAGE 2 ALIAS RECOVERY RUNNER: PASS'}catch{Write-Host 'CFA STAGE 2 ALIAS RECOVERY RUNNER: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
