#requires -Version 5.1
[CmdletBinding()]
param([string]$RepoRoot='',[switch]$SelfTest)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$AllowedPaths=@('docs/evidence/stage2-alias-recovery.md','docs/evidence/stage2-alias-recovery.csv','docs/evidence/stage2-alias-recovery-samples.csv','docs/evidence/stage2-alias-quarantine.csv')
function Invoke-Git{param([string]$Root,[string[]]$Args);Push-Location $Root;$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';$o=@(& git @Args 2>&1);$c=$LASTEXITCODE;$t=($o|ForEach-Object{[string]$_})-join[Environment]::NewLine;if($c-ne0){throw "git $($Args-join' ') failed $c`n$t"};return $t.Trim()}finally{$ErrorActionPreference=$old;Pop-Location}}
function Split-Lines{param([AllowEmptyString()][string]$Text);if([string]::IsNullOrWhiteSpace($Text)){return @()};return @($Text-split"`r?`n"|Where-Object{-not[string]::IsNullOrWhiteSpace($_)})}
function Assert-Allowed{param([AllowEmptyString()][string]$Status);foreach($line in @(Split-Lines $Status)){$ok=$false;foreach($p in $AllowedPaths){if($line.EndsWith($p)-or$line.EndsWith($p.Replace('/','\'))){$ok=$true;break}};if(-not$ok){throw "Unexpected working-tree change during alias recovery sync: $line"}}}
function Assert-Paths{param([string[]]$Paths);foreach($p in @($Paths)){if([string]::IsNullOrWhiteSpace($p)){continue};if($AllowedPaths-notcontains$p){throw "Unexpected staged path: $p"}}}
function Invoke-SelfTest{$s="?? docs/evidence/stage2-alias-recovery.md`n?? docs/evidence/stage2-alias-quarantine.csv";Assert-Allowed $s;$x=@(Split-Lines "docs/evidence/stage2-alias-recovery.md`ndocs/evidence/stage2-alias-quarantine.csv");if($x.Count-ne2){throw 'line split'};Assert-Paths $x;$blocked=$false;try{Assert-Allowed " M README.md"}catch{$blocked=$true};if(-not$blocked){throw 'unrelated change not blocked'};Write-Host 'SELF-TEST: PASS'}
if($SelfTest){try{Invoke-SelfTest;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;exit 1}}
try{if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).ProviderPath;$branch=Invoke-Git $RepoRoot @('branch','--show-current');if([string]::IsNullOrWhiteSpace($branch)){throw 'Branch unresolved.'};$pre=Invoke-Git $RepoRoot @('status','--porcelain','--untracked-files=all');Assert-Allowed $pre;[void](Invoke-Git $RepoRoot @('pull','--ff-only','origin',$branch));$publisher=Join-Path $RepoRoot 'scripts\windows\Publish-CfaStage2AliasRecovery.ps1';& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $publisher -SelfTest;if($LASTEXITCODE-ne0){throw 'Publisher self-test failed.'};& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $publisher;if($LASTEXITCODE-ne0){throw 'Publisher failed.'};$after=Invoke-Git $RepoRoot @('status','--porcelain','--untracked-files=all');Assert-Allowed $after;if(@(Split-Lines $after).Count-gt0){[void](Invoke-Git $RepoRoot (@('add','--')+$AllowedPaths));$staged=@(Split-Lines (Invoke-Git $RepoRoot @('diff','--cached','--name-only')));Assert-Paths $staged;if($staged.Count-gt0){[void](Invoke-Git $RepoRoot @('commit','-m','Update CFA Stage 2 alias recovery evidence'));[void](Invoke-Git $RepoRoot @('push','origin',$branch))}};[void](Invoke-Git $RepoRoot @('fetch','origin',$branch));$local=Invoke-Git $RepoRoot @('rev-parse','HEAD');$remote=Invoke-Git $RepoRoot @('rev-parse',"origin/$branch");if($local-ne$remote){throw "Local/remote mismatch $local $remote"};$final=Invoke-Git $RepoRoot @('status','--porcelain','--untracked-files=all');if(-not[string]::IsNullOrWhiteSpace($final)){throw "Repository not clean.`n$final"};Write-Host "Published alias recovery evidence commit: $local";Write-Host 'CFA STAGE 2 ALIAS RECOVERY SYNC: PASS'}catch{Write-Host 'CFA STAGE 2 ALIAS RECOVERY SYNC: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
