#requires -Version 5.1
[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$RunReceiptPath,
 [string]$PgHost='localhost',[ValidateRange(1,65535)][int]$PgPort=5432,[string]$PgUser='postgres',
 [ValidateRange(60,1800)][int]$StatementTimeoutSeconds=900,[string]$RepoRoot='',[string]$OutputRoot='',[switch]$SelfTest
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$Inv=[Globalization.CultureInfo]::InvariantCulture
$ExpectedStage10ProfileSha='2d625ed8a79f17cf2a6ac21e22fea62fa3a1a04f9cfa51d9b0ec7ef861e304fd';$ExpectedAf001Sha='569522ec450ab1870ffa1386f4e356e4047cf6ef017c77a98a3bedcf331f416f';$ExpectedAssets=418;$ExpectedScans=8639;$ExpectedMarketRows=14055089L;$ExpectedMarketPairs=1058;$ExpectedSlots=8736;$ExpectedDl=7163;$ExpectedPm=1573
$Q2Start=[datetime]::SpecifyKind([datetime]'2025-04-01T00:00:00',[DateTimeKind]::Utc);$Q2End=[datetime]::SpecifyKind([datetime]'2025-07-01T00:00:00',[DateTimeKind]::Utc);$FirstScan=$Q2Start.AddDays(1).AddMinutes(15)
if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))};$RepoRoot=(Resolve-Path $RepoRoot).ProviderPath
function Sha-S11v2{param($p);(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function File-S11v2{param($p,$l);$x=(Resolve-Path -LiteralPath $p -ErrorAction Stop).ProviderPath;if(-not(Test-Path $x -PathType Leaf)){throw "$l missing: $x"};$x}
function Bool-S11v2{param($v);$x=([string]$v).Trim().ToLowerInvariant();if($x-in@('true','t')){$true}elseif($x-in@('false','f')){$false}else{throw "Malformed bool: $v"}}
function Utc-S11v2{param([datetime]$d);$d.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss'Z'",$Inv)}
function Window-S11v2{param([datetime]$s,[int]$h,[hashtable]$slots);$need=$h*4;$end=$s.AddMinutes(-15);$start=$end.AddHours(-$h);$dl=0;$pm=0;$miss=0;for($i=0;$i-lt$need;$i++){$k=$start.AddMinutes(15*$i).ToString('yyyyMMddHHmmss',$Inv);if(-not$slots.ContainsKey($k)){$miss++;continue};$st=[string]$slots[$k].status;if($st-ceq'downloaded'){$dl++}elseif($st-ceq'provider_missing'){$pm++}else{throw "Unexpected slot status $st"}};[pscustomobject]@{complete=($dl-eq$need-and$pm-eq0-and$miss-eq0);downloaded=$dl;provider_missing=$pm;registry_missing=$miss}}
function FindPsql-S11v2{$c=Get-Command psql.exe -CommandType Application -ErrorAction SilentlyContinue|Select-Object -First 1;if($null-ne$c){return $c.Source};$f=@(Get-ChildItem 'C:\Program Files\PostgreSQL\*\bin\psql.exe' -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending);if($f.Count-eq0){throw 'psql.exe not found'};$f[0].FullName}
function PsqlText-S11v2{param($exe,$sql);$e=[IO.Path]::GetTempFileName();try{$o=@(& $exe -X -h $PgHost -p $PgPort -U $PgUser -d asrp -A -t -q -v ON_ERROR_STOP=1 -c $sql 2>$e);$c=$LASTEXITCODE;$er=(Get-Content $e -ErrorAction SilentlyContinue)-join[Environment]::NewLine;$t=($o|ForEach-Object{[string]$_})-join[Environment]::NewLine;if($c-ne0){throw "psql failed ($c).`n$er`n$t"};$t}finally{Remove-Item $e -Force -ErrorAction SilentlyContinue}}
function PsqlCsv-S11v2{param($e,$q);PsqlText-S11v2 $e "COPY (`n$($q.Trim())`n) TO STDOUT WITH (FORMAT CSV, HEADER TRUE);"}
function Near-S11v2{param($a,$b,[double]$tol=1e-10);if([string]::IsNullOrWhiteSpace([string]$a)-and[string]::IsNullOrWhiteSpace([string]$b)){return $true};$x=0.0;$y=0.0;if(-not[double]::TryParse([string]$a,[Globalization.NumberStyles]::Float,$Inv,[ref]$x)){return $false};if(-not[double]::TryParse([string]$b,[Globalization.NumberStyles]::Float,$Inv,[ref]$y)){return $false};[math]::Abs($x-$y)-le($tol*[math]::Max(1.0,[math]::Max([math]::Abs($x),[math]::Abs($y))))}
function Json-S11v2{param($p,$v);[IO.File]::WriteAllText($p,(($v|ConvertTo-Json -Depth 12)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
function SelfTest-S11v2{$slots=@{};$s=$Q2Start;for($i=0;$i-lt96;$i++){$slots[$s.AddMinutes(15*$i).ToString('yyyyMMddHHmmss',$Inv)]=[pscustomobject]@{status='downloaded'}};$w=Window-S11v2 $FirstScan 24 $slots;if(-not$w.complete-or$w.downloaded-ne96){throw 'news window self-test'};if(-not(Near-S11v2 '1.0' '1')){throw 'near self-test'};Write-Host 'SELF-TEST: PASS'}
if($SelfTest){try{SelfTest-S11v2;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;exit 1}}
$oldPwd=$env:PGPASSWORD;$oldOpt=$env:PGOPTIONS;$b=[IntPtr]::Zero
try{
 $RunReceiptPath=File-S11v2 $RunReceiptPath 'Stage 11 V2 receipt';$runSha=Sha-S11v2 $RunReceiptPath;$r=Get-Content $RunReceiptPath -Raw|ConvertFrom-Json;if([string]$r.status-ne'VALIDATION_CANDIDATE'-or[string]$r.run-ne'SCANNER_SOURCE_READINESS_V2'){throw 'Not a Stage 11 V2 candidate'}
 $v1Path=File-S11v2 ([string]$r.prior_v1_receipt) 'prior V1 receipt';if((Sha-S11v2 $v1Path)-ne[string]$r.prior_v1_receipt_sha256){throw 'Prior V1 receipt hash mismatch'};$v1=Get-Content $v1Path -Raw|ConvertFrom-Json
 foreach($n in @('source_entry_reconciliation','news_scan_window_readiness','news_readiness_summary','market_readiness_summary','market_breadth_readiness')){$p=File-S11v2 ([string]$r.outputs.$n) $n;if((Sha-S11v2 $p)-ne[string]$r.outputs.($n+'_sha256')){throw "V2 output hash mismatch: $n"}}
 $entry=Get-Content ([string]$r.outputs.source_entry_reconciliation) -Raw|ConvertFrom-Json;$profilePath=File-S11v2 ([string]$entry.stage10.profile) 'Stage 10 profile';if((Sha-S11v2 $profilePath)-ne$ExpectedStage10ProfileSha){throw 'Stage10 profile hash mismatch'};$assets=@((Import-Csv $profilePath)|ForEach-Object{[string]$_.base_asset_id}|Sort-Object -Unique);if($assets.Count-ne$ExpectedAssets){throw 'Stage10 asset count mismatch'}
 $slotsPath=File-S11v2 ([string]$entry.stage5.source_slots) 'source slots';$slotRows=@(Import-Csv $slotsPath);if($slotRows.Count-ne$ExpectedSlots){throw 'Source slot count mismatch'};$slots=@{};$dl=0;$pm=0;foreach($x in $slotRows){$k=[string]$x.slot_key;if($slots.ContainsKey($k)){throw "Duplicate slot $k"};$slots[$k]=$x;if([string]$x.status-ceq'downloaded'){$dl++}elseif([string]$x.status-ceq'provider_missing'){$pm++}else{throw 'Unexpected source status'}};if($dl-ne$ExpectedDl-or$pm-ne$ExpectedPm){throw 'Source slot partition mismatch'}
 $news=@(Import-Csv ([string]$r.outputs.news_scan_window_readiness));if($news.Count-ne$ExpectedScans){throw 'News scan count mismatch'};$n24=0;$n6=0;$both=0;$i=0;for($s=$FirstScan;$s-lt$Q2End;$s=$s.AddMinutes(15)){$o=$news[$i];$ts=Utc-S11v2 $s;if([string]$o.scan_timestamp_utc-ne$ts){throw "News timestamp mismatch $i"};$w24=Window-S11v2 $s 24 $slots;$w6=Window-S11v2 $s 6 $slots;if((Bool-S11v2 $o.news24_complete)-ne$w24.complete-or[int]$o.news24_downloaded_slots-ne$w24.downloaded-or[int]$o.news24_provider_missing_slots-ne$w24.provider_missing-or[int]$o.news24_registry_missing_slots-ne$w24.registry_missing){throw "24h news mismatch $ts"};if((Bool-S11v2 $o.news6_complete)-ne$w6.complete-or[int]$o.news6_downloaded_slots-ne$w6.downloaded-or[int]$o.news6_provider_missing_slots-ne$w6.provider_missing-or[int]$o.news6_registry_missing_slots-ne$w6.registry_missing){throw "6h news mismatch $ts"};if($w24.complete){$n24++};if($w6.complete){$n6++};if($w24.complete-and$w6.complete){$both++};$i++};if($n24-ne6593-or$n6-ne6953-or$both-ne6593){throw "News totals changed: $n24/$n6/$both"}
 $afPath=File-S11v2 (Join-Path $RepoRoot 'candidate-analysis\ASRP-Q2-Pair-Identity-Frozen-v1.0.0.csv') 'AF001';if((Sha-S11v2 $afPath)-ne$ExpectedAf001Sha){throw 'AF001 hash mismatch'};$usd=@((Import-Csv $afPath)|Where-Object{(Bool-S11v2 $_.research_eligible)-and([string]$_.quote_exchange_symbol).Trim()-ceq'USD'});$map=@{};foreach($x in $usd){$map[[string]$x.base_asset_id]=$x};$vals=New-Object Collections.ArrayList;foreach($a in $assets){if(-not$map.ContainsKey($a)){throw "No USD map $a"};[void]$vals.Add("("+([string]$map[$a].source_member_ordinal).Trim()+",'"+$a.Replace("'","''")+"')")};$values=$vals.ToArray()-join','
 $psql=FindPsql-S11v2;$secure=Read-Host "PostgreSQL password for '$PgUser'" -AsSecureString;$b=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure);$env:PGPASSWORD=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b);$env:PGOPTIONS="-c default_transaction_read_only=on -c statement_timeout=$($StatementTimeoutSeconds*1000)";$version=(PsqlText-S11v2 $psql 'SHOW server_version;').Trim();$ro=(PsqlText-S11v2 $psql "SELECT current_setting('default_transaction_read_only');").Trim();if($ro-ne'on'){throw 'PostgreSQL not read-only'};$card=@((PsqlCsv-S11v2 $psql "SELECT count(*)::bigint row_count,count(DISTINCT pair_token_opaque)::int pair_count FROM asrp.q2_market_1m_observations")|ConvertFrom-Csv)[0];if([long]$card.row_count-ne$ExpectedMarketRows-or[int]$card.pair_count-ne$ExpectedMarketPairs){throw 'Market cardinality mismatch'}
 $q=@"
WITH scanner_assets(source_member_ordinal,base_asset_id) AS (VALUES $values),bins AS MATERIALIZED (
 SELECT m.source_member_ordinal,date_bin(interval '15 minutes',m.candle_start_utc,timestamptz '2025-04-01 00:00:00+00') bin_start,count(*)::int obs_count,min(m.candle_start_utc) first_ts,max(m.candle_start_utc) last_ts
 FROM asrp.q2_market_1m_observations m JOIN scanner_assets a USING(source_member_ordinal)
 WHERE m.candle_start_utc>=timestamptz '2025-04-01 00:00:00+00' AND m.candle_start_utc<timestamptz '2025-07-01 00:00:00+00' AND m.canonical_eligible AND m.in_source_window AND m.minute_aligned AND cardinality(m.quality_flags)=0 AND m.duplicate_class IS NULL
 GROUP BY m.source_member_ordinal,date_bin(interval '15 minutes',m.candle_start_utc,timestamptz '2025-04-01 00:00:00+00')),
grid AS MATERIALIZED (SELECT a.base_asset_id,g.bin_start,coalesce(b.obs_count,0)::int obs_count,b.first_ts,b.last_ts FROM scanner_assets a CROSS JOIN generate_series(timestamptz '2025-04-01 00:00:00+00',timestamptz '2025-06-30 23:45:00+00',interval '15 minutes')g(bin_start) LEFT JOIN bins b ON b.source_member_ordinal=a.source_member_ordinal AND b.bin_start=g.bin_start),
roll AS MATERIALIZED (SELECT base_asset_id,bin_start+interval '15 minutes' scan_ts,
 sum(obs_count)OVER(PARTITION BY base_asset_id ORDER BY bin_start RANGE BETWEEN interval '45 minutes' PRECEDING AND CURRENT ROW)obs60,min(first_ts)OVER(PARTITION BY base_asset_id ORDER BY bin_start RANGE BETWEEN interval '45 minutes' PRECEDING AND CURRENT ROW)first60,max(last_ts)OVER(PARTITION BY base_asset_id ORDER BY bin_start RANGE BETWEEN interval '45 minutes' PRECEDING AND CURRENT ROW)last60,
 sum(obs_count)OVER(PARTITION BY base_asset_id ORDER BY bin_start RANGE BETWEEN interval '225 minutes' PRECEDING AND CURRENT ROW)obs240,min(first_ts)OVER(PARTITION BY base_asset_id ORDER BY bin_start RANGE BETWEEN interval '225 minutes' PRECEDING AND CURRENT ROW)first240,max(last_ts)OVER(PARTITION BY base_asset_id ORDER BY bin_start RANGE BETWEEN interval '225 minutes' PRECEDING AND CURRENT ROW)last240 FROM grid),
x AS MATERIALIZED (SELECT base_asset_id,scan_ts,v.horizon_minutes,v.obs_count,v.first_ts,v.last_ts,CASE WHEN v.obs_count>0 THEN extract(epoch FROM(v.last_ts-v.first_ts))/60.0 END span_minutes,CASE WHEN v.obs_count>0 THEN extract(epoch FROM(v.first_ts-(scan_ts-make_interval(mins=>v.horizon_minutes))))/60.0 END start_gap_minutes,CASE WHEN v.obs_count>0 THEN extract(epoch FROM(scan_ts-v.last_ts))/60.0 END end_gap_minutes FROM roll CROSS JOIN LATERAL(VALUES(60,obs60,first60,last60),(240,obs240,first240,last240))v(horizon_minutes,obs_count,first_ts,last_ts) WHERE scan_ts>=timestamptz '2025-04-02 00:15:00+00' AND scan_ts<timestamptz '2025-07-01 00:00:00+00'),
a AS (SELECT 'A' typ,base_asset_id,NULL::text scan_timestamp_utc,horizon_minutes,count(*)::bigint scan_count,count(*)FILTER(WHERE obs_count>0)::bigint windows_with_any,count(*)FILTER(WHERE obs_count>0)::double precision/count(*) any_share,min(obs_count)::double precision min_obs,percentile_disc(.10)WITHIN GROUP(ORDER BY obs_count)::double precision p10_obs,percentile_disc(.50)WITHIN GROUP(ORDER BY obs_count)::double precision median_obs,percentile_disc(.90)WITHIN GROUP(ORDER BY obs_count)::double precision p90_obs,max(obs_count)::double precision max_obs,percentile_disc(.50)WITHIN GROUP(ORDER BY span_minutes)FILTER(WHERE obs_count>0)::double precision median_span_minutes,percentile_disc(.90)WITHIN GROUP(ORDER BY span_minutes)FILTER(WHERE obs_count>0)::double precision p90_span_minutes,percentile_disc(.50)WITHIN GROUP(ORDER BY start_gap_minutes)FILTER(WHERE obs_count>0)::double precision median_start_gap_minutes,percentile_disc(.90)WITHIN GROUP(ORDER BY start_gap_minutes)FILTER(WHERE obs_count>0)::double precision p90_start_gap_minutes,percentile_disc(.50)WITHIN GROUP(ORDER BY end_gap_minutes)FILTER(WHERE obs_count>0)::double precision median_end_gap_minutes,percentile_disc(.90)WITHIN GROUP(ORDER BY end_gap_minutes)FILTER(WHERE obs_count>0)::double precision p90_end_gap_minutes,NULL::int assets_with_any,NULL::double precision breadth_share FROM x GROUP BY base_asset_id,horizon_minutes),
b AS (SELECT 'B' typ,NULL::text base_asset_id,to_char(scan_ts AT TIME ZONE 'UTC','YYYY-MM-DD')||'T'||to_char(scan_ts AT TIME ZONE 'UTC','HH24:MI:SS')||'Z' scan_timestamp_utc,horizon_minutes,NULL::bigint scan_count,NULL::bigint windows_with_any,NULL::double precision any_share,NULL::double precision min_obs,NULL::double precision p10_obs,NULL::double precision median_obs,NULL::double precision p90_obs,NULL::double precision max_obs,NULL::double precision median_span_minutes,NULL::double precision p90_span_minutes,NULL::double precision median_start_gap_minutes,NULL::double precision p90_start_gap_minutes,NULL::double precision median_end_gap_minutes,NULL::double precision p90_end_gap_minutes,count(*)FILTER(WHERE obs_count>0)::int assets_with_any,count(*)FILTER(WHERE obs_count>0)::double precision/418.0 breadth_share FROM x GROUP BY scan_ts,horizon_minutes)
SELECT * FROM a UNION ALL SELECT * FROM b ORDER BY typ,base_asset_id NULLS LAST,scan_timestamp_utc NULLS LAST,horizon_minutes
"@
 $calc=@((PsqlCsv-S11v2 $psql $q)|ConvertFrom-Csv);$ca=@($calc|Where-Object{$_.typ-eq'A'});$cb=@($calc|Where-Object{$_.typ-eq'B'});$oa=@(Import-Csv ([string]$r.outputs.market_readiness_summary));$ob=@(Import-Csv ([string]$r.outputs.market_breadth_readiness);if($ca.Count-ne836-or$oa.Count-ne836-or$cb.Count-ne17278-or$ob.Count-ne17278){throw 'Market output row count mismatch'}
 $caBy=@{};foreach($x in $ca){$caBy[([string]$x.base_asset_id)+'|'+([string]$x.horizon_minutes)]=$x};foreach($o in $oa){$k=([string]$o.base_asset_id)+'|'+([string]$o.horizon_minutes);$c=$caBy[$k];foreach($n in @('scan_count','windows_with_any')){if([long]$o.$n-ne[long]$c.$n){throw "$k $n mismatch"}};foreach($n in @('any_share','min_obs','p10_obs','median_obs','p90_obs','max_obs','median_span_minutes','p90_span_minutes','median_start_gap_minutes','p90_start_gap_minutes','median_end_gap_minutes','p90_end_gap_minutes')){if(-not(Near-S11v2 $o.$n $c.$n)){throw "$k $n mismatch"}}}
 $bad=@($ob|Where-Object{([string]$_.scan_timestamp_utc)-notmatch'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$'});if($bad.Count-ne0){throw "Malformed V2 breadth timestamps: $($bad.Count)"};$dup=@($ob|Group-Object scan_timestamp_utc,horizon_minutes|Where-Object{$_.Count-ne1});if($dup.Count-ne0){throw "Duplicate V2 breadth keys: $($dup.Count)"};$cbBy=@{};foreach($x in $cb){$k=([string]$x.scan_timestamp_utc)+'|'+([string]$x.horizon_minutes);if($cbBy.ContainsKey($k)){throw "Independent duplicate breadth key $k"};$cbBy[$k]=$x};foreach($o in $ob){$k=([string]$o.scan_timestamp_utc)+'|'+([string]$o.horizon_minutes);if(-not$cbBy.ContainsKey($k)){throw "Missing breadth key $k"};$c=$cbBy[$k];if([int]$o.assets_with_any-ne[int]$c.assets_with_any){throw "$k assets_with_any mismatch: observed=$($o.assets_with_any) expected=$($c.assets_with_any)"};if(-not(Near-S11v2 $o.breadth_share $c.breadth_share)){throw "$k breadth_share mismatch"}}
 if([string]::IsNullOrWhiteSpace($OutputRoot)){$OutputRoot=Split-Path -Parent $RunReceiptPath};$checks=Join-Path $OutputRoot 'stage11-source-readiness-v2-independent-validation-checks.csv';$vr=Join-Path $OutputRoot 'stage11-source-readiness-v2-independent-validation.json';@([pscustomobject]@{check_id='S11V2-001';status='PASS';detail='V2 receipt and prior V1 lineage/hash reconciliation'},[pscustomobject]@{check_id='S11V2-002';status='PASS';detail='8639 news scans independently recomputed'},[pscustomobject]@{check_id='S11V2-003';status='PASS';detail='836 market summary rows independently recomputed with RANGE windows'},[pscustomobject]@{check_id='S11V2-004';status='PASS';detail='17278 canonical unique breadth rows independently recomputed'},[pscustomobject]@{check_id='S11V2-005';status='PASS';detail='No forward outcomes inspected'})|Export-Csv $checks -NoTypeInformation -Encoding UTF8;$rec=[ordered]@{status='PASS';stage='CFA_STAGE_11_INDEPENDENT_VALIDATION';run='SCANNER_SOURCE_READINESS_V2';candidate_receipt=$RunReceiptPath;candidate_receipt_sha256=$runSha;postgresql_version=$version;default_transaction_read_only=$ro;counts=[ordered]@{scanner_assets=418;candidate_scans=8639;news24_complete=$n24;news6_complete=$n6;both_news_complete=$both;market_summary_rows=836;market_breadth_rows=17278};checks_csv=$checks;checks_sha256=(Sha-S11v2 $checks);gates=[ordered]@{'CFA-S11-006'='PASS';'CFA-S11-007'='UNVERIFIED';'CFA-S11-008'='BLOCKED'}};Json-S11v2 $vr $rec
 Write-Host '';Write-Host 'CFA STAGE 11 V2 INDEPENDENT SCANNER SOURCE READINESS VALIDATION: PASS';Write-Host "Scanner assets / candidate scans: 418 / 8639";Write-Host "GDELT 24h / 6h / both complete scans: $n24 / $n6 / $both";Write-Host 'Market readiness rows asset-summary / breadth: 836 / 17278';Write-Host 'Breadth timestamps canonical and unique: True';Write-Host 'Forward outcomes inspected: False';Write-Host 'CFA-S11-006 independent validation: PASS';Write-Host "Validation receipt: $vr";exit 0
}catch{Write-Host '';Write-Host 'CFA STAGE 11 V2 INDEPENDENT SCANNER SOURCE READINESS VALIDATION: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}finally{if($b-ne[IntPtr]::Zero){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b)};$env:PGPASSWORD=$oldPwd;$env:PGOPTIONS=$oldOpt}
