#requires -Version 5.1
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$RunReceiptPath,
    [string]$RepoRoot='',
    [string]$OutputRoot='',
    [switch]$SelfTest
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Invariant=[Globalization.CultureInfo]::InvariantCulture

$ExpectedStage7ValidationReceiptSha='e3e9088e511b74e875e1bccc3e8d292acc9c49209c93943117195f8ace5b3756'
$ExpectedStage9ValidationReceiptSha='fee93242132aa46dd11a6f969a49679d51559533a9870255cc928f4a875079bf'
$ExpectedStage9RunReceiptSha='f505f5a3210d543aaa71a5bf352cbb8849c8cb2237923aa7dc018f65cfe5abda'
$ExpectedModelReadySha='fc0498881957688acffd6fe3805ac96037ca884304bff9964e1e248b4ec0e024'
$NewsFactors=@('NEWS_V6_MATCH_COUNT_24H_LAG15','NEWS_V6_MATCH_COUNT_6H_LAG15','NEWS_V6_SOURCE_COUNT_24H_LAG15')

if([string]::IsNullOrWhiteSpace($RepoRoot)){$RepoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).ProviderPath

function Get-S10vSha {param([string]$Path);return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Require-S10vFile {param([string]$Path,[string]$Label);$r=(Resolve-Path -LiteralPath $Path -ErrorAction Stop).ProviderPath;if(-not(Test-Path -LiteralPath $r -PathType Leaf)){throw "$Label is not a file: $r"};return $r}
function Parse-S10vDouble {param([object]$Value,[string]$Label);$n=0.0;if(-not[double]::TryParse(([string]$Value),[Globalization.NumberStyles]::Float,$Invariant,[ref]$n)){throw "Malformed numeric for ${Label}: '$Value'"};if([double]::IsNaN($n)-or[double]::IsInfinity($n)){throw "Non-finite numeric for ${Label}: '$Value'"};return $n}
function Near-S10v {param([double]$A,[double]$B,[double]$Tolerance=1e-10);$scale=[math]::Max(1.0,[math]::Max([math]::Abs($A),[math]::Abs($B)));return [math]::Abs($A-$B)-le($Tolerance*$scale)}
function Mean-S10v {param([System.Collections.IList]$Values);if($Values.Count-lt1){return [double]::NaN};$sum=0.0;foreach($v in $Values){$sum+=[double]$v};return $sum/$Values.Count}
function Sd-S10v {param([System.Collections.IList]$Values);if($Values.Count-lt2){return [double]::NaN};$m=Mean-S10v $Values;$ss=0.0;foreach($v in $Values){$d=[double]$v-$m;$ss+=$d*$d};return [math]::Sqrt($ss/($Values.Count-1))}
function Pearson-S10v {param([System.Collections.IList]$A,[System.Collections.IList]$B);if($A.Count-ne$B.Count-or$A.Count-lt2){return [double]::NaN};$ma=Mean-S10v $A;$mb=Mean-S10v $B;$cross=0.0;$aa=0.0;$bb=0.0;for($i=0;$i-lt$A.Count;$i++){$da=[double]$A[$i]-$ma;$db=[double]$B[$i]-$mb;$cross+=$da*$db;$aa+=$da*$da;$bb+=$db*$db};if($aa-le0-or$bb-le0){return [double]::NaN};return $cross/[math]::Sqrt($aa*$bb)}
function P90-S10v {param([System.Collections.IList]$Values);if($Values.Count-lt1){return [double]::NaN};[double[]]$s=@($Values|ForEach-Object{[double]$_}|Sort-Object);$rank=[int][math]::Ceiling(0.9*$s.Count);if($rank-lt1){$rank=1};return [double]$s[$rank-1]}
function Median-S10v {param([System.Collections.IList]$Values);if($Values.Count-lt1){return [double]::NaN};[double[]]$s=@($Values|ForEach-Object{[double]$_}|Sort-Object);$n=$s.Count;if(($n%2)-eq1){return [double]$s[[int](($n-1)/2)]};$l=[int]($n/2-1);$r=[int]($n/2);return ([double]$s[$l]+[double]$s[$r])/2.0}
function TestMaybeNaN-S10v {param([object]$Observed,[double]$Expected,[string]$Label);if([double]::IsNaN($Expected)){if(([string]$Observed)-ne'NaN'){throw "$Label expected NaN, observed '$Observed'"};return};$o=Parse-S10vDouble $Observed $Label;if(-not(Near-S10v $o $Expected)){throw "$Label mismatch: observed=$o expected=$Expected"}}

function Metric-S10v {
    param([object[]]$Rows,[string]$Asset,[string]$Surface,[string]$FactorId)
    $factor=New-Object System.Collections.ArrayList;$signed=New-Object System.Collections.ArrayList;$abs=New-Object System.Collections.ArrayList;$zS=New-Object System.Collections.ArrayList;$pS=New-Object System.Collections.ArrayList;$zA=New-Object System.Collections.ArrayList;$pA=New-Object System.Collections.ArrayList
    $min=[double]::PositiveInfinity;$max=[double]::NegativeInfinity
    foreach($row in $Rows){$fv=Parse-S10vDouble $row.PSObject.Properties[$FactorId].Value "$Asset $Surface $FactorId";$rv=Parse-S10vDouble $row.response_value_log_return "$Asset $Surface response";[void]$factor.Add($fv);[void]$signed.Add($rv);[void]$abs.Add([math]::Abs($rv));if($fv-lt$min){$min=$fv};if($fv-gt$max){$max=$fv};if($fv-eq0){[void]$zS.Add($rv);[void]$zA.Add([math]::Abs($rv))}else{[void]$pS.Add($rv);[void]$pA.Add([math]::Abs($rv))}}
    $n=$Rows.Count;$zero=$zS.Count;$positive=$pS.Count;$support=if($n-ge20-and$zero-ge5-and$positive-ge5){'SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC'}else{'INSUFFICIENT_SUPPORT'};$zm=Mean-S10v $zS;$pm=Mean-S10v $pS;$zam=Mean-S10v $zA;$pam=Mean-S10v $pA
    $de=if([double]::IsNaN($zm)-or[double]::IsNaN($pm)){[double]::NaN}else{$pm-$zm};$me=if([double]::IsNaN($zam)-or[double]::IsNaN($pam)){[double]::NaN}else{$pam-$zam}
    return [pscustomobject]@{base_asset_id=$Asset;surface=$Surface;factor_id=$FactorId;n=$n;zero_news_rows=$zero;positive_news_rows=$positive;news_coverage_rate=$positive/[double]$n;mean=(Mean-S10v $factor);sample_sd=(Sd-S10v $factor);min=$min;max=$max;pearson_signed_return=(Pearson-S10v $factor $signed);pearson_absolute_return=(Pearson-S10v $factor $abs);mean_signed_zero=$zm;mean_signed_positive=$pm;direction_effect_positive_minus_zero=$de;mean_absolute_zero=$zam;mean_absolute_positive=$pam;magnitude_effect_positive_minus_zero=$me;directional_support=$support;magnitude_support=if($support-eq'SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC'){'SUFFICIENT_FOR_MAGNITUDE_DIAGNOSTIC'}else{'INSUFFICIENT_SUPPORT'}}
}
function Stability-S10v {param($Earlier,$Later,[string]$Property);if($Earlier.directional_support-ne'SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC'-or$Later.directional_support-ne'SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC'){return 'UNRESOLVED_SUPPORT'};$a=[double]$Earlier.$Property;$b=[double]$Later.$Property;if([double]::IsNaN($a)-or[double]::IsNaN($b)){return 'UNRESOLVED_SUPPORT'};if(($a-lt0-and$b-gt0)-or($a-gt0-and$b-lt0)){return 'SIGN_REVERSAL'};return 'SAME_SIGN'}

function DayCache-S10v {param([object[]]$Rows);$cache=@{};foreach($g in ($Rows|Group-Object response_day_utc)){$ordered=@($g.Group|Sort-Object @{Expression={[double]$_.response_value_log_return}},base_asset_id);$values=[double[]]::new($ordered.Count);$idx=@{};for($i=0;$i-lt$ordered.Count;$i++){$values[$i]=Parse-S10vDouble $ordered[$i].response_value_log_return 'day return';$idx[[string]$ordered[$i].base_asset_id]=$i};$cache[[string]$g.Name]=[pscustomobject]@{values=$values;index_by_asset=$idx;n=$ordered.Count;median=(Median-S10v $values)}};return $cache}
function LeaveOneOut-S10v {param($Day,[string]$Asset);$n=[int]$Day.n;if($n-lt2){return [double]::NaN};$remove=[int]$Day.index_by_asset[$Asset];$remaining=$n-1;if(($remaining%2)-eq1){$k=[int](($remaining-1)/2);$orig=if($remove-le$k){$k+1}else{$k};return [double]$Day.values[$orig]};$k1=[int]($remaining/2-1);$k2=[int]($remaining/2);$o1=if($remove-le$k1){$k1+1}else{$k1};$o2=if($remove-le$k2){$k2+1}else{$k2};return ([double]$Day.values[$o1]+[double]$Day.values[$o2])/2.0}
function RollingFit-S10v {param([object[]]$History,$DayMap,[string]$Asset);if($History.Count-lt15){return $null};$use=@($History|Select-Object -Last 20);$x=New-Object System.Collections.ArrayList;$y=New-Object System.Collections.ArrayList;foreach($row in $use){$day=[string]$row.response_day_utc;$m=LeaveOneOut-S10v $DayMap[$day] $Asset;if(-not[double]::IsNaN($m)){[void]$x.Add($m);[void]$y.Add((Parse-S10vDouble $row.response_value_log_return 'rolling response'))}};if($x.Count-lt15){return $null};$xm=Mean-S10v $x;$ym=Mean-S10v $y;$cross=0.0;$xx=0.0;for($i=0;$i-lt$x.Count;$i++){$dx=[double]$x[$i]-$xm;$cross+=$dx*([double]$y[$i]-$ym);$xx+=$dx*$dx};if($xx-le0){return $null};$beta=$cross/$xx;return [pscustomobject]@{n=$x.Count;alpha=$ym-$beta*$xm;beta=$beta}}

function AssertMetric-S10v {param($Observed,$Expected,[string]$Label);foreach($name in @('n','zero_news_rows','positive_news_rows')){if([int]$Observed.$name-ne[int]$Expected.$name){throw "$Label $name mismatch"}};foreach($name in @('news_coverage_rate','mean','sample_sd','min','max','pearson_signed_return','pearson_absolute_return','mean_signed_zero','mean_signed_positive','direction_effect_positive_minus_zero','mean_absolute_zero','mean_absolute_positive','magnitude_effect_positive_minus_zero')){TestMaybeNaN-S10v $Observed.$name ([double]$Expected.$name) "$Label $name"};if([string]$Observed.directional_support-ne[string]$Expected.directional_support-or[string]$Observed.magnitude_support-ne[string]$Expected.magnitude_support){throw "$Label support mismatch"}}

function SelfTest-S10v {
    if((P90-S10v @(1,2,3,4,5,6,7,8,9,10))-ne9){throw 'p90 self-test failed'};if((Median-S10v @(1,2,3,4))-ne2.5){throw 'median self-test failed'}
    $cache=[pscustomobject]@{n=4;values=[double[]]@(1,2,3,4);index_by_asset=@{A=0;B=1;C=2;D=3}};if((LeaveOneOut-S10v $cache 'B')-ne3){throw 'leave-one-out self-test failed'}
    $rows=@([pscustomobject]@{response_value_log_return='1';F='0'},[pscustomobject]@{response_value_log_return='2';F='1'},[pscustomobject]@{response_value_log_return='3';F='2'},[pscustomobject]@{response_value_log_return='4';F='0'},[pscustomobject]@{response_value_log_return='5';F='1'},[pscustomobject]@{response_value_log_return='6';F='0'},[pscustomobject]@{response_value_log_return='7';F='1'},[pscustomobject]@{response_value_log_return='8';F='0'},[pscustomobject]@{response_value_log_return='9';F='1'},[pscustomobject]@{response_value_log_return='10';F='0'},[pscustomobject]@{response_value_log_return='11';F='1'},[pscustomobject]@{response_value_log_return='12';F='0'},[pscustomobject]@{response_value_log_return='13';F='1'},[pscustomobject]@{response_value_log_return='14';F='0'},[pscustomobject]@{response_value_log_return='15';F='1'},[pscustomobject]@{response_value_log_return='16';F='0'},[pscustomobject]@{response_value_log_return='17';F='1'},[pscustomobject]@{response_value_log_return='18';F='0'},[pscustomobject]@{response_value_log_return='19';F='1'},[pscustomobject]@{response_value_log_return='20';F='0'})
    $m=Metric-S10v $rows 'A' 'ALL' 'F';if($m.directional_support-ne'SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC'){throw 'metric support self-test failed'}
    Write-Host 'SELF-TEST: PASS'
}
if($SelfTest){try{SelfTest-S10v;exit 0}catch{Write-Host 'SELF-TEST: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}}

try {
    $contract=Get-Content -LiteralPath (Require-S10vFile (Join-Path $RepoRoot 'docs\evidence\stage10-symbol-heterogeneity-contract.md') 'Stage 10 contract') -Raw
    foreach($marker in @('SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC','MARKET_MEDIAN_EX_A','LARGE_MOVE','NEWS_ASSOCIATED_ABNORMAL','SCANNER_DESIGN_BLOCKED')){if($contract-notmatch[regex]::Escape($marker)){throw "Stage 10 contract marker missing: $marker"}}
    $RunReceiptPath=Require-S10vFile $RunReceiptPath 'Stage 10 run receipt';$runSha=Get-S10vSha $RunReceiptPath;$receipt=Get-Content -LiteralPath $RunReceiptPath -Raw|ConvertFrom-Json
    if([string]$receipt.status-ne'VALIDATION_CANDIDATE'-or[string]$receipt.stage-ne'CFA_STAGE_10'-or[string]$receipt.run-ne'SYMBOL_HETEROGENEITY_V1'){throw 'Stage 10 run receipt identity mismatch'}
    if([string]$receipt.sources.stage7_validation_receipt_sha256-ne$ExpectedStage7ValidationReceiptSha-or[string]$receipt.sources.stage9_validation_receipt_sha256-ne$ExpectedStage9ValidationReceiptSha-or[string]$receipt.sources.model_ready_sha256-ne$ExpectedModelReadySha){throw 'Stage 10 source hash mismatch'}
    foreach($g in 1..6){$id=('CFA-S10-{0:D3}'-f$g);if([string]$receipt.gates.$id-ne'PASS'){throw "Candidate prerequisite gate not PASS: $id"}}

    $stage7Path=Require-S10vFile ([string]$receipt.sources.stage7_validation_receipt) 'Stage 7 receipt';$stage9Path=Require-S10vFile ([string]$receipt.sources.stage9_validation_receipt) 'Stage 9 receipt';if((Get-S10vSha $stage7Path)-ne$ExpectedStage7ValidationReceiptSha-or(Get-S10vSha $stage9Path)-ne$ExpectedStage9ValidationReceiptSha){throw 'Frozen receipt file hash mismatch'}
    $stage9=Get-Content -LiteralPath $stage9Path -Raw|ConvertFrom-Json;if([string]$stage9.run_receipt_sha256-ne$ExpectedStage9RunReceiptSha){throw 'Stage 9 run receipt lineage mismatch'}
    $stage7=Get-Content -LiteralPath $stage7Path -Raw|ConvertFrom-Json;$modelPath=Require-S10vFile ([string]$stage7.outputs.model_ready) 'Model-ready CSV';if((Get-S10vSha $modelPath)-ne$ExpectedModelReadySha){throw 'Model-ready hash mismatch'}

    $paths=@{sensitivity=Require-S10vFile ([string]$receipt.outputs.symbol_news_sensitivity) 'Sensitivity CSV';stability=Require-S10vFile ([string]$receipt.outputs.symbol_temporal_stability) 'Stability CSV';profile=Require-S10vFile ([string]$receipt.outputs.symbol_profile_summary) 'Profile CSV';market=Require-S10vFile ([string]$receipt.outputs.market_reference_by_day) 'Market reference CSV';events=Require-S10vFile ([string]$receipt.outputs.symbol_event_attribution) 'Events CSV';event_summary=Require-S10vFile ([string]$receipt.outputs.event_attribution_summary_by_symbol) 'Event summary CSV'}
    foreach($pair in @(@('sensitivity','symbol_news_sensitivity_sha256'),@('stability','symbol_temporal_stability_sha256'),@('profile','symbol_profile_summary_sha256'),@('market','market_reference_by_day_sha256'),@('events','symbol_event_attribution_sha256'),@('event_summary','event_attribution_summary_by_symbol_sha256'))){if((Get-S10vSha $paths[$pair[0]])-ne[string]$receipt.outputs.PSObject.Properties[$pair[1]].Value){throw "Candidate output hash mismatch: $($pair[0])"}}

    $model=@(Import-Csv -LiteralPath $modelPath);if($model.Count-ne26337){throw 'Model-ready row count mismatch'};$assets=@($model|ForEach-Object{[string]$_.base_asset_id}|Sort-Object -Unique);$days=@($model|ForEach-Object{[string]$_.response_day_utc}|Sort-Object -Unique);if($assets.Count-ne418-or$days.Count-ne66){throw 'Model-ready asset/day cardinality mismatch'}

    $candidateSensitivity=@(Import-Csv -LiteralPath $paths.sensitivity);$candidateSensitivityMap=@{};foreach($r in $candidateSensitivity){$k=([string]$r.base_asset_id)+'|'+([string]$r.surface)+'|'+([string]$r.factor_id);if($candidateSensitivityMap.ContainsKey($k)){throw "Duplicate sensitivity key: $k"};$candidateSensitivityMap[$k]=$r}
    $metricMap=@{};$expectedSensitivityCount=0
    foreach($asset in $assets){$assetRows=@($model|Where-Object{[string]$_.base_asset_id-ceq$asset}|Sort-Object response_day_utc);foreach($surface in @('ALL','TRAIN','VALIDATION','TEST')){$surfaceRows=@();if($surface-eq'ALL'){$surfaceRows=@($assetRows)}else{$surfaceRows=@($assetRows|Where-Object{[string]$_.design_role-eq$surface})};if($surfaceRows.Count-lt1){continue};foreach($factorId in $NewsFactors){$m=Metric-S10v $surfaceRows $asset $surface $factorId;$k=$asset+'|'+$surface+'|'+$factorId;if(-not$candidateSensitivityMap.ContainsKey($k)){throw "Missing sensitivity key: $k"};AssertMetric-S10v $candidateSensitivityMap[$k] $m $k;$metricMap[$k]=$m;$expectedSensitivityCount++}}}
    if($candidateSensitivity.Count-ne$expectedSensitivityCount){throw "Sensitivity row count mismatch: observed=$($candidateSensitivity.Count) expected=$expectedSensitivityCount"}

    $candidateStability=@(Import-Csv -LiteralPath $paths.stability);$candidateStabilityMap=@{};foreach($r in $candidateStability){$k=([string]$r.base_asset_id)+'|'+([string]$r.factor_id)+'|'+([string]$r.earlier_surface)+'|'+([string]$r.later_surface);$candidateStabilityMap[$k]=$r};$stabilityComputed=New-Object System.Collections.ArrayList
    foreach($asset in $assets){foreach($factorId in $NewsFactors){foreach($pair in @(@('TRAIN','VALIDATION'),@('VALIDATION','TEST'),@('TRAIN','TEST'))){$e=$metricMap[$asset+'|'+$pair[0]+'|'+$factorId];$l=$metricMap[$asset+'|'+$pair[1]+'|'+$factorId];if($null-eq$e-or$null-eq$l){continue};$obj=[pscustomobject]@{base_asset_id=$asset;factor_id=$factorId;earlier_surface=$pair[0];later_surface=$pair[1];signed_correlation_stability=(Stability-S10v $e $l 'pearson_signed_return');direction_effect_stability=(Stability-S10v $e $l 'direction_effect_positive_minus_zero');absolute_correlation_stability=(Stability-S10v $e $l 'pearson_absolute_return');magnitude_effect_stability=(Stability-S10v $e $l 'magnitude_effect_positive_minus_zero')};[void]$stabilityComputed.Add($obj);$k=$asset+'|'+$factorId+'|'+$pair[0]+'|'+$pair[1];$o=$candidateStabilityMap[$k];if($null-eq$o){throw "Missing stability key: $k"};foreach($name in @('signed_correlation_stability','direction_effect_stability','absolute_correlation_stability','magnitude_effect_stability')){if([string]$o.$name-ne[string]$obj.$name){throw "$k $name mismatch"}}}}}
    if($candidateStability.Count-ne$stabilityComputed.Count){throw 'Stability row count mismatch'}

    $dayMap=DayCache-S10v $model;$candidateMarket=@(Import-Csv -LiteralPath $paths.market);if($candidateMarket.Count-ne$days.Count){throw 'Market reference row count mismatch'};for($i=0;$i-lt$days.Count;$i++){$day=$days[$i];$o=$candidateMarket[$i];if([string]$o.response_day_utc-cne$day-or[int]$o.n_assets-ne[int]$dayMap[$day].n){throw "Market reference identity mismatch: $day"};TestMaybeNaN-S10v $o.market_median_return ([double]$dayMap[$day].median) "market median $day"}

    $candidateEvents=@(Import-Csv -LiteralPath $paths.events);if($candidateEvents.Count-ne$model.Count){throw 'Event row count mismatch'};$candidateEventMap=@{};foreach($r in $candidateEvents){$k=([string]$r.base_asset_id)+'|'+([string]$r.response_day_utc);if($candidateEventMap.ContainsKey($k)){throw "Duplicate event key: $k"};$candidateEventMap[$k]=$r}
    $summaryComputed=@{};$newsSymbols=@{};$marketSymbols=@{}
    foreach($asset in $assets){$assetRows=@($model|Where-Object{[string]$_.base_asset_id-ceq$asset}|Sort-Object response_day_utc);$counts=@{large=0;classified=0;market=0;news=0;mixed=0;specific=0};for($i=0;$i-lt$assetRows.Count;$i++){$row=$assetRows[$i];$day=[string]$row.response_day_utc;$response=Parse-S10vDouble $row.response_value_log_return "$asset $day response";$history=@();if($i-gt0){$history=@($assetRows[0..($i-1)])};$recent=@($history|Select-Object -Last 20);$threshold=[double]::NaN;$large=$false;$support=$recent.Count-ge10;if($support){$ah=New-Object System.Collections.ArrayList;foreach($h in $recent){[void]$ah.Add([math]::Abs((Parse-S10vDouble $h.response_value_log_return 'event history')))};$threshold=P90-S10v $ah;$large=[math]::Abs($response)-gt$threshold}
        $b24=$false;$b6=$false;$bs=$false;$q24=[double]::NaN;$q6=[double]::NaN;$qs=[double]::NaN;if($recent.Count-ge10){$v24=New-Object System.Collections.ArrayList;$v6=New-Object System.Collections.ArrayList;$vs=New-Object System.Collections.ArrayList;foreach($h in $recent){[void]$v24.Add((Parse-S10vDouble $h.NEWS_V6_MATCH_COUNT_24H_LAG15 'h24'));[void]$v6.Add((Parse-S10vDouble $h.NEWS_V6_MATCH_COUNT_6H_LAG15 'h6'));[void]$vs.Add((Parse-S10vDouble $h.NEWS_V6_SOURCE_COUNT_24H_LAG15 'hs'))};$q24=P90-S10v $v24;$q6=P90-S10v $v6;$qs=P90-S10v $vs;$c24=Parse-S10vDouble $row.NEWS_V6_MATCH_COUNT_24H_LAG15 'c24';$c6=Parse-S10vDouble $row.NEWS_V6_MATCH_COUNT_6H_LAG15 'c6';$cs=Parse-S10vDouble $row.NEWS_V6_SOURCE_COUNT_24H_LAG15 'cs';$b24=$c24-gt0-and$c24-gt$q24;$b6=$c6-gt0-and$c6-gt$q6;$bs=$cs-gt0-and$cs-gt$qs}
        $marketEx=LeaveOneOut-S10v $dayMap[$day] $asset;$fit=RollingFit-S10v $history $dayMap $asset;$mc=[double]::NaN;$ab=[double]::NaN;$label='UNVERIFIED_EVENT_SUPPORT';if($support){if(-not$large){$label='NON_EVENT'}elseif($null-eq$fit){$label='UNVERIFIED'}else{$mc=$fit.alpha+$fit.beta*$marketEx;$ab=$response-$mc;$any=$b24-or$b6-or$bs;if([math]::Abs($mc)-ge[math]::Abs($ab)){$label=if($any){'MIXED'}else{'MARKET_DOMINANT'}}else{$label=if($any){'NEWS_ASSOCIATED_ABNORMAL'}else{'SYMBOL_SPECIFIC_NO_NEWS'}}}}
        $k=$asset+'|'+$day;$o=$candidateEventMap[$k];if($null-eq$o){throw "Missing event key: $k"};foreach($name in @('base_asset_id','response_day_utc','design_role','event_attribution')){$expected=if($name-eq'base_asset_id'){$asset}elseif($name-eq'response_day_utc'){$day}elseif($name-eq'design_role'){[string]$row.design_role}else{$label};if([string]$o.$name-cne[string]$expected){throw "$k $name mismatch"}};if(([string]$o.large_move)-ne([string]$large)){throw "$k large_move mismatch"};$rn=if($null-eq$fit){0}else{$fit.n};if([int]$o.rolling_market_n-ne$rn){throw "$k rolling_market_n mismatch"}
        $expectedAlpha=[double]::NaN;$expectedBeta=[double]::NaN;if($null-ne$fit){$expectedAlpha=[double]$fit.alpha;$expectedBeta=[double]$fit.beta}
        foreach($pair in @(@('response_value_log_return',$response),@('abs_response',[math]::Abs($response)),@('event_threshold_q90_abs_return',$threshold),@('market_median_ex_asset',$marketEx),@('rolling_alpha',$expectedAlpha),@('rolling_beta',$expectedBeta),@('market_component',$mc),@('abnormal_return',$ab),@('news24_q90',$q24),@('news6_q90',$q6),@('source24_q90',$qs))){TestMaybeNaN-S10v $o.PSObject.Properties[$pair[0]].Value ([double]$pair[1]) "$k $($pair[0])"};foreach($pair in @(@('news_burst_24h',$b24),@('news_burst_6h',$b6),@('source_burst_24h',$bs))){if(([string]$o.PSObject.Properties[$pair[0]].Value)-ne([string]$pair[1])){throw "$k $($pair[0]) mismatch"}}
        if($large){$counts.large++};if($label-in@('MARKET_DOMINANT','NEWS_ASSOCIATED_ABNORMAL','MIXED','SYMBOL_SPECIFIC_NO_NEWS')){$counts.classified++;if($label-eq'MARKET_DOMINANT'){$counts.market++};if($label-eq'NEWS_ASSOCIATED_ABNORMAL'){$counts.news++};if($label-eq'MIXED'){$counts.mixed++};if($label-eq'SYMBOL_SPECIFIC_NO_NEWS'){$counts.specific++}}
      };$summaryComputed[$asset]=[pscustomobject]@{rows=$assetRows.Count;large_move_events=$counts.large;classified_large_move_events=$counts.classified;market_dominant_events=$counts.market;news_associated_abnormal_events=$counts.news;mixed_events=$counts.mixed;symbol_specific_no_news_events=$counts.specific};if($counts.news-gt0){$newsSymbols[$asset]=$true};if($counts.market-gt0){$marketSymbols[$asset]=$true}}

    $candidateSummary=@(Import-Csv -LiteralPath $paths.event_summary);if($candidateSummary.Count-ne$assets.Count){throw 'Event summary row count mismatch'};$summaryMap=@{};foreach($r in $candidateSummary){$summaryMap[[string]$r.base_asset_id]=$r};foreach($asset in $assets){$o=$summaryMap[$asset];$e=$summaryComputed[$asset];if($null-eq$o){throw "Missing event summary: $asset"};foreach($name in @('rows','large_move_events','classified_large_move_events','market_dominant_events','news_associated_abnormal_events','mixed_events','symbol_specific_no_news_events')){if([int]$o.$name-ne[int]$e.$name){throw "$asset summary $name mismatch"}};$newsShare=if($e.classified_large_move_events-gt0){$e.news_associated_abnormal_events/[double]$e.classified_large_move_events}else{[double]::NaN};$marketShare=if($e.classified_large_move_events-gt0){$e.market_dominant_events/[double]$e.classified_large_move_events}else{[double]::NaN};TestMaybeNaN-S10v $o.news_associated_abnormal_share $newsShare "$asset news share";TestMaybeNaN-S10v $o.market_dominant_share $marketShare "$asset market share"}

    $candidateProfile=@(Import-Csv -LiteralPath $paths.profile);if($candidateProfile.Count-ne$assets.Count){throw 'Profile row count mismatch'};$profileMap=@{};foreach($r in $candidateProfile){$profileMap[[string]$r.base_asset_id]=$r};$sufficient24=0
    foreach($asset in $assets){$o=$profileMap[$asset];if($null-eq$o){throw "Missing profile: $asset"};$m24=$metricMap[$asset+'|ALL|NEWS_V6_MATCH_COUNT_24H_LAG15'];$m6=$metricMap[$asset+'|ALL|NEWS_V6_MATCH_COUNT_6H_LAG15'];$ms=$metricMap[$asset+'|ALL|NEWS_V6_SOURCE_COUNT_24H_LAG15'];$suff=$m24.directional_support-eq'SUFFICIENT_FOR_DIRECTIONAL_DIAGNOSTIC';if($suff){$sufficient24++};$reversals=0;foreach($f in $NewsFactors){$st=$candidateStabilityMap[$asset+'|'+$f+'|TRAIN|TEST'];if($null-ne$st-and($st.signed_correlation_stability-eq'SIGN_REVERSAL'-or$st.direction_effect_stability-eq'SIGN_REVERSAL')){$reversals++}};foreach($pair in @(@('n',$m24.n),@('news24_coverage_rate',$m24.news_coverage_rate),@('news24_direction_effect',$m24.direction_effect_positive_minus_zero),@('news24_magnitude_effect',$m24.magnitude_effect_positive_minus_zero),@('news24_signed_correlation',$m24.pearson_signed_return),@('news24_absolute_correlation',$m24.pearson_absolute_return),@('news6_coverage_rate',$m6.news_coverage_rate),@('news6_direction_effect',$m6.direction_effect_positive_minus_zero),@('news6_magnitude_effect',$m6.magnitude_effect_positive_minus_zero),@('source24_coverage_rate',$ms.news_coverage_rate),@('source24_direction_effect',$ms.direction_effect_positive_minus_zero),@('source24_magnitude_effect',$ms.magnitude_effect_positive_minus_zero),@('train_test_direction_reversal_indicators',$reversals),@('large_move_events',$summaryComputed[$asset].large_move_events),@('classified_large_move_events',$summaryComputed[$asset].classified_large_move_events),@('news_associated_abnormal_events',$summaryComputed[$asset].news_associated_abnormal_events),@('market_dominant_events',$summaryComputed[$asset].market_dominant_events))){if($pair[0]-in@('n','train_test_direction_reversal_indicators','large_move_events','classified_large_move_events','news_associated_abnormal_events','market_dominant_events')){if([int]$o.PSObject.Properties[$pair[0]].Value-ne[int]$pair[1]){throw "$asset profile $($pair[0]) mismatch"}}else{TestMaybeNaN-S10v $o.PSObject.Properties[$pair[0]].Value ([double]$pair[1]) "$asset profile $($pair[0])"}};if(([string]$o.sufficient_all_24h)-ne([string]$suff)){throw "$asset sufficient flag mismatch"};$e=$summaryComputed[$asset];$ns=if($e.classified_large_move_events-gt0){$e.news_associated_abnormal_events/[double]$e.classified_large_move_events}else{[double]::NaN};$msr=if($e.classified_large_move_events-gt0){$e.market_dominant_events/[double]$e.classified_large_move_events}else{[double]::NaN};TestMaybeNaN-S10v $o.news_associated_abnormal_share $ns "$asset profile news share";TestMaybeNaN-S10v $o.market_dominant_share $msr "$asset profile market share"}

    if([int]$receipt.counts.rows-ne26337-or[int]$receipt.counts.assets-ne418-or[int]$receipt.counts.days-ne66-or[int]$receipt.counts.sufficient_24h_symbols-ne$sufficient24-or[int]$receipt.counts.symbols_with_news_associated_abnormal_events-ne$newsSymbols.Count-or[int]$receipt.counts.symbols_with_market_dominant_events-ne$marketSymbols.Count){throw 'Run receipt count reconciliation mismatch'}

    if([string]::IsNullOrWhiteSpace($OutputRoot)){$OutputRoot=Split-Path -Parent $RunReceiptPath};New-Item -ItemType Directory -Path $OutputRoot -Force|Out-Null;$checksPath=Join-Path $OutputRoot 'stage10-symbol-heterogeneity-independent-validation-checks.csv';$validationPath=Join-Path $OutputRoot 'stage10-symbol-heterogeneity-independent-validation.json'
    $checks=@([pscustomobject]@{check_id='FROZEN_ENTRY';status='PASS';detail='Stage 7/9 receipts and model-ready hash reconciled'},[pscustomobject]@{check_id='PER_SYMBOL_METRICS';status='PASS';detail="All $expectedSensitivityCount per-symbol factor rows independently recomputed"},[pscustomobject]@{check_id='TEMPORAL_STABILITY';status='PASS';detail="All $($stabilityComputed.Count) stability rows independently recomputed"},[pscustomobject]@{check_id='MARKET_REFERENCE';status='PASS';detail='All 66 daily market references independently recomputed'},[pscustomobject]@{check_id='EVENT_ATTRIBUTION';status='PASS';detail='All 26337 event rows independently recomputed from trailing-only baselines'},[pscustomobject]@{check_id='PROFILE_SUMMARY';status='PASS';detail='All 418 profile and event-summary rows reconciled'},[pscustomobject]@{check_id='OUTPUT_HASHES';status='PASS';detail='All Stage 10 candidate output hashes match run receipt'})
    $checks|Export-Csv -LiteralPath $checksPath -NoTypeInformation -Encoding UTF8
    $validation=[ordered]@{status='PASS';stage='CFA_STAGE_10';validation='INDEPENDENT_SYMBOL_HETEROGENEITY_V1';run_receipt=$RunReceiptPath;run_receipt_sha256=$runSha;sources=[ordered]@{stage7_validation_receipt_sha256=$ExpectedStage7ValidationReceiptSha;stage9_validation_receipt_sha256=$ExpectedStage9ValidationReceiptSha;stage9_run_receipt_sha256=$ExpectedStage9RunReceiptSha;model_ready_sha256=$ExpectedModelReadySha};counts=[ordered]@{rows=26337;assets=418;days=66;sufficient_24h_symbols=$sufficient24;symbols_with_news_associated_abnormal_events=$newsSymbols.Count;symbols_with_market_dominant_events=$marketSymbols.Count};candidate_outputs=[ordered]@{symbol_news_sensitivity_sha256=(Get-S10vSha $paths.sensitivity);symbol_temporal_stability_sha256=(Get-S10vSha $paths.stability);symbol_profile_summary_sha256=(Get-S10vSha $paths.profile);market_reference_by_day_sha256=(Get-S10vSha $paths.market);symbol_event_attribution_sha256=(Get-S10vSha $paths.events);event_attribution_summary_by_symbol_sha256=(Get-S10vSha $paths.event_summary)};validation_checks=$checksPath;validation_checks_sha256=(Get-S10vSha $checksPath);gates=[ordered]@{'CFA-S10-001'='PASS';'CFA-S10-002'='PASS';'CFA-S10-003'='PASS';'CFA-S10-004'='PASS';'CFA-S10-005'='PASS';'CFA-S10-006'='PASS';'CFA-S10-007'='PASS';'CFA-S10-008'='UNVERIFIED'};next_action='Pin exact Stage 10 run/output/independent-validation hashes in repository evidence before scanner design.'}
    [IO.File]::WriteAllText($validationPath,(($validation|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))
    Write-Host '';Write-Host 'CFA STAGE 10 INDEPENDENT SYMBOL HETEROGENEITY VALIDATION: PASS';Write-Host 'Rows / assets / days: 26337 / 418 / 66';Write-Host "Symbols with sufficient ALL-period 24h news support: $sufficient24";Write-Host "Symbols with >=1 NEWS_ASSOCIATED_ABNORMAL large-move event: $($newsSymbols.Count)";Write-Host "Symbols with >=1 MARKET_DOMINANT large-move event: $($marketSymbols.Count)";Write-Host 'CFA-S10-007 independent validation: PASS';Write-Host 'CFA-S10-008 scanner prerequisites freeze: UNVERIFIED';Write-Host "Run receipt SHA-256: $runSha";foreach($pair in @(@('Symbol news sensitivity',$paths.sensitivity),@('Temporal stability',$paths.stability),@('Profile summary',$paths.profile),@('Market reference',$paths.market),@('Event attribution',$paths.events),@('Event summary',$paths.event_summary))){Write-Host "$($pair[0]) SHA-256: $(Get-S10vSha $pair[1])"};Write-Host "Validation checks SHA-256: $(Get-S10vSha $checksPath)";Write-Host "Validation receipt SHA-256: $(Get-S10vSha $validationPath)";Write-Host "Validation checks: $checksPath";Write-Host "Validation receipt: $validationPath";exit 0
}
catch {Write-Host '';Write-Host 'CFA STAGE 10 INDEPENDENT SYMBOL HETEROGENEITY VALIDATION: FAIL';Write-Host $_.Exception.Message;if($_.ScriptStackTrace){Write-Host $_.ScriptStackTrace};exit 1}
